from __future__ import annotations

import hashlib
import os
from collections.abc import Iterable, Iterator
from pathlib import Path

from app.storage.base import StorageWriteResult


class LocalFileStorage:
    """Filesystem-backed StorageBackend. Intended to sit on a Render
    persistent disk in production -- Core cannot provision that disk itself;
    without it, files written here do not survive a redeploy. Storage keys
    are always generated by the caller as {organization_id}/{artifact_id}/
    source (see SourceArtifact registration) -- never a client filename, so
    there is no path-traversal surface from user input reaching this class.
    """

    def __init__(self, root: str) -> None:
        self._root = Path(root)
        self._root.mkdir(parents=True, exist_ok=True)

    def _path_for(self, key: str) -> Path:
        # Defense in depth even though callers only ever pass generated
        # keys: reject any key that could escape the storage root.
        candidate = (self._root / key).resolve()
        root_resolved = self._root.resolve()
        if root_resolved not in candidate.parents and candidate != root_resolved:
            raise ValueError(f"storage key resolves outside storage root: {key!r}")
        return candidate

    def write_stream(self, key: str, chunks: Iterable[bytes]) -> StorageWriteResult:
        path = self._path_for(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        digest = hashlib.sha256()
        size = 0
        # Write to a temp file first, then atomically rename -- a reader
        # never observes a partially-written file at the final path.
        tmp_path = path.with_suffix(path.suffix + ".part")
        try:
            with tmp_path.open("wb") as handle:
                for chunk in chunks:
                    handle.write(chunk)
                    digest.update(chunk)
                    size += len(chunk)
            os.replace(tmp_path, path)
        except BaseException:
            tmp_path.unlink(missing_ok=True)
            raise
        return StorageWriteResult(reference=key, size_bytes=size, checksum=digest.hexdigest())

    def open_stream(self, reference: str) -> Iterator[bytes]:
        path = self._path_for(reference)
        with path.open("rb") as handle:
            while chunk := handle.read(1024 * 1024):
                yield chunk

    def cleanup(self, reference: str) -> None:
        self._path_for(reference).unlink(missing_ok=True)
