from app.models.entities import MembershipRole

ORGANIZATION_READ_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
    MembershipRole.RECOVERY_MANAGER,
    MembershipRole.VIEWER,
)
ORGANIZATION_ADMIN_ROLES = (MembershipRole.ORGANIZATION_ADMIN,)
MAINTENANCE_ANALYSIS_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
RECOVERY_WRITE_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.OPERATOR,
    MembershipRole.RECOVERY_MANAGER,
)
SOURCE_SYSTEM_READ_ROLES = ORGANIZATION_READ_ROLES
SOURCE_SYSTEM_ADMIN_ROLES = ORGANIZATION_ADMIN_ROLES
SOURCE_SYSTEM_OPERATIONS_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.OPERATOR,
)
INGESTION_READ_ROLES = ORGANIZATION_READ_ROLES
INGESTION_ADMIN_ROLES = ORGANIZATION_ADMIN_ROLES
INGESTION_OPERATION_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.OPERATOR,
)
INGESTION_RELEASE_ROLES = ORGANIZATION_ADMIN_ROLES
RAW_LINEAGE_READ_ROLES = ORGANIZATION_READ_ROLES
RAW_LINEAGE_OPERATION_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.OPERATOR,
)
RAW_LINEAGE_ANALYSIS_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
RAW_LINEAGE_GOVERNANCE_ROLES = ORGANIZATION_ADMIN_ROLES
TRUST_READ_ROLES = ORGANIZATION_READ_ROLES
TRUST_EXECUTION_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
INTELLIGENCE_READ_ROLES = ORGANIZATION_READ_ROLES
INTELLIGENCE_EXECUTION_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
INTELLIGENCE_REQUEST_ROLES = INTELLIGENCE_EXECUTION_ROLES
INTELLIGENCE_OPERATOR_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.OPERATOR,
)
FINDING_READ_ROLES = ORGANIZATION_READ_ROLES
FINDING_REVIEW_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
FINDING_ADMIN_ROLES = ORGANIZATION_ADMIN_ROLES
OIKB_READ_ROLES = ORGANIZATION_READ_ROLES
OIKB_AUTHOR_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
)
OIKB_VALIDATION_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
)
OIKB_GOVERNANCE_ROLES = ORGANIZATION_ADMIN_ROLES
STATISTICAL_EXECUTION_READ_ROLES = ORGANIZATION_READ_ROLES
STATISTICAL_EXECUTION_RUN_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
STATISTICAL_METHOD_READ_ROLES = ORGANIZATION_READ_ROLES
STATISTICAL_REVIEW_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
STATISTICAL_SUPPRESSION_MANAGE_ROLES = ORGANIZATION_ADMIN_ROLES
STATISTICAL_ADMINISTER_ROLES = ORGANIZATION_ADMIN_ROLES
FORECAST_EXECUTION_READ_ROLES = ORGANIZATION_READ_ROLES
FORECAST_EXECUTION_RUN_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
FORECAST_METHOD_READ_ROLES = ORGANIZATION_READ_ROLES
FORECAST_SCENARIO_CREATE_ROLES = FORECAST_EXECUTION_RUN_ROLES
FORECAST_SCENARIO_APPROVE_ROLES = ORGANIZATION_ADMIN_ROLES
FORECAST_REVISION_CREATE_ROLES = FORECAST_EXECUTION_RUN_ROLES
FORECAST_ACTUAL_REGISTER_ROLES = FORECAST_EXECUTION_RUN_ROLES
FORECAST_ACCURACY_READ_ROLES = ORGANIZATION_READ_ROLES
FORECAST_ADMINISTER_ROLES = ORGANIZATION_ADMIN_ROLES
RELIABILITY_EXECUTION_READ_ROLES = ORGANIZATION_READ_ROLES
RELIABILITY_EXECUTION_RUN_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
RELIABILITY_METHOD_READ_ROLES = ORGANIZATION_READ_ROLES
RELIABILITY_ASSESSMENT_REVIEW_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
RELIABILITY_HEALTH_READ_ROLES = ORGANIZATION_READ_ROLES
RELIABILITY_RISK_READ_ROLES = ORGANIZATION_READ_ROLES
RELIABILITY_PM_REVIEW_ROLES = ORGANIZATION_ADMIN_ROLES
RELIABILITY_ADMINISTER_ROLES = ORGANIZATION_ADMIN_ROLES
ACTION_READ_ROLES = ORGANIZATION_READ_ROLES
ACTION_CREATE_ROLES = INTELLIGENCE_EXECUTION_ROLES
ACTION_ASSIGN_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.OPERATOR,
    MembershipRole.RECOVERY_MANAGER,
)
ACTION_APPROVE_ROLES = ORGANIZATION_ADMIN_ROLES
ACTION_PLAN_ROLES = ACTION_ASSIGN_ROLES
ACTION_TRANSITION_ROLES = ACTION_ASSIGN_ROLES
ACTION_VERIFY_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.RECOVERY_MANAGER,
)
ACTION_OUTCOME_ROLES = ACTION_VERIFY_ROLES
ACTION_FEEDBACK_ROLES = ACTION_VERIFY_ROLES
ECONOMICS_READ_ROLES = ORGANIZATION_READ_ROLES
ECONOMICS_WRITE_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
    MembershipRole.RECOVERY_MANAGER,
)
ECONOMICS_CALCULATE_ROLES = ECONOMICS_WRITE_ROLES
ECONOMICS_APPROVE_ROLES = ORGANIZATION_ADMIN_ROLES
ECONOMICS_PORTFOLIO_ROLES = ORGANIZATION_READ_ROLES
RECOVERY_LEDGER_READ_ROLES = ORGANIZATION_READ_ROLES
RECOVERY_MEASUREMENT_ROLES = RECOVERY_WRITE_ROLES
RECOVERY_FINANCE_ROLES = ORGANIZATION_ADMIN_ROLES
COMMERCIAL_READ_ROLES = ORGANIZATION_READ_ROLES
COMMERCIAL_ADMIN_ROLES = ORGANIZATION_ADMIN_ROLES
SIGNATURE_READ_ROLES = ORGANIZATION_READ_ROLES
SIGNATURE_EXECUTION_ROLES = INTELLIGENCE_EXECUTION_ROLES
SIGNATURE_ADMIN_ROLES = ORGANIZATION_ADMIN_ROLES
KNOWLEDGE_GRAPH_READ_ROLES = ORGANIZATION_READ_ROLES
KNOWLEDGE_GRAPH_TRAVERSAL_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
    MembershipRole.RECOVERY_MANAGER,
)
KNOWLEDGE_GRAPH_PROJECTION_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.OPERATOR,
)
