from app.models.entities import MembershipRole

ORGANIZATION_READ_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
    MembershipRole.RECOVERY_MANAGER,
    MembershipRole.VIEWER,
)
ORGANIZATION_ADMIN_ROLES = (MembershipRole.ORGANIZATION_ADMIN,)
MAINTENANCE_ANALYSIS_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
RECOVERY_WRITE_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.OPERATOR,
    MembershipRole.RECOVERY_MANAGER,
)
SOURCE_SYSTEM_READ_ROLES = ORGANIZATION_READ_ROLES
SOURCE_SYSTEM_ADMIN_ROLES = ORGANIZATION_ADMIN_ROLES
SOURCE_SYSTEM_OPERATIONS_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.OPERATOR,
)
INGESTION_READ_ROLES = ORGANIZATION_READ_ROLES
INGESTION_ADMIN_ROLES = ORGANIZATION_ADMIN_ROLES
INGESTION_OPERATION_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.OPERATOR,
)
INGESTION_RELEASE_ROLES = ORGANIZATION_ADMIN_ROLES
RAW_LINEAGE_READ_ROLES = ORGANIZATION_READ_ROLES
RAW_LINEAGE_OPERATION_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.OPERATOR,
)
RAW_LINEAGE_ANALYSIS_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
RAW_LINEAGE_GOVERNANCE_ROLES = ORGANIZATION_ADMIN_ROLES
TRUST_READ_ROLES = ORGANIZATION_READ_ROLES
TRUST_EXECUTION_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
INTELLIGENCE_READ_ROLES = ORGANIZATION_READ_ROLES
INTELLIGENCE_EXECUTION_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
INTELLIGENCE_REQUEST_ROLES = INTELLIGENCE_EXECUTION_ROLES
INTELLIGENCE_OPERATOR_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.OPERATOR,
)
FINDING_READ_ROLES = ORGANIZATION_READ_ROLES
FINDING_REVIEW_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
FINDING_ADMIN_ROLES = ORGANIZATION_ADMIN_ROLES
OIKB_READ_ROLES = ORGANIZATION_READ_ROLES
OIKB_AUTHOR_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
)
OIKB_VALIDATION_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
)
OIKB_GOVERNANCE_ROLES = ORGANIZATION_ADMIN_ROLES
STATISTICAL_EXECUTION_READ_ROLES = ORGANIZATION_READ_ROLES
STATISTICAL_EXECUTION_RUN_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
STATISTICAL_METHOD_READ_ROLES = ORGANIZATION_READ_ROLES
STATISTICAL_REVIEW_ROLES = (
    MembershipRole.ORGANIZATION_ADMIN,
    MembershipRole.ANALYST,
    MembershipRole.OPERATOR,
)
STATISTICAL_SUPPRESSION_MANAGE_ROLES = ORGANIZATION_ADMIN_ROLES
STATISTICAL_ADMINISTER_ROLES = ORGANIZATION_ADMIN_ROLES
