# ruff: noqa: E501
"""raw storage and lineage foundation

Revision ID: 20260724_0005
Revises: 20260724_0004
Create Date: 2026-07-24 18:35:43.470504
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260724_0005"
down_revision: str | None = "20260724_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lineage_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("node_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("entity_reference", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "node_type IN ('source_system', 'ingestion_batch', 'dataset', 'dataset_version', 'raw_storage_object', 'raw_record_reference', 'processing_run', 'custom')",
            name="ck_lineage_node_type",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'superseded', 'unavailable', 'archived')",
            name="ck_lineage_node_status",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "node_type", "entity_id", name="uq_lineage_node_entity"
        ),
    )
    op.create_index("ix_lineage_nodes_entity_id", "lineage_nodes", ["entity_id"], unique=False)
    op.create_index("ix_lineage_nodes_node_type", "lineage_nodes", ["node_type"], unique=False)
    op.create_index(
        "ix_lineage_nodes_organization_id", "lineage_nodes", ["organization_id"], unique=False
    )
    op.create_table(
        "processing_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("ingestion_batch_id", sa.Uuid(), nullable=True),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=True),
        sa.Column("run_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("executor_type", sa.String(length=30), nullable=False),
        sa.Column("executor_reference", sa.String(length=255), nullable=True),
        sa.Column("correlation_id", sa.String(length=255), nullable=True),
        sa.Column("parent_run_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_count", sa.Integer(), nullable=False),
        sa.Column("output_count", sa.Integer(), nullable=False),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_summary", sa.Text(), nullable=True),
        sa.Column(
            "parameters_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "metrics_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "executor_type IN ('user', 'service', 'worker', 'agent', 'scheduled_job', 'external_system', 'simulation')",
            name="ck_run_executor_type",
        ),
        sa.CheckConstraint(
            "run_type IN ('integrity_verification', 'decompression', 'extraction', 'parsing', 'schema_discovery', 'segmentation', 'normalization', 'mapping', 'trust_assessment', 'custom')",
            name="ck_run_type",
        ),
        sa.CheckConstraint(
            "status IN ('created', 'queued', 'running', 'completed', 'partially_completed', 'failed', 'cancelled', 'quarantined')",
            name="ck_run_status",
        ),
        sa.CheckConstraint(
            "input_count >= 0 AND output_count >= 0 AND warning_count >= 0 AND error_count >= 0",
            name="ck_run_counts_nonnegative",
        ),
        sa.CheckConstraint(
            "parent_run_id IS NULL OR parent_run_id != id", name="ck_run_not_own_parent"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_batch_id"], ["ingestion_batches.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["parent_run_id"], ["processing_runs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_processing_runs_batch_id", "processing_runs", ["ingestion_batch_id"], unique=False
    )
    op.create_index(
        "ix_processing_runs_correlation_id", "processing_runs", ["correlation_id"], unique=False
    )
    op.create_index(
        "ix_processing_runs_dataset_version_id",
        "processing_runs",
        ["dataset_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_processing_runs_organization_id", "processing_runs", ["organization_id"], unique=False
    )
    op.create_index("ix_processing_runs_run_type", "processing_runs", ["run_type"], unique=False)
    op.create_index("ix_processing_runs_status", "processing_runs", ["status"], unique=False)
    op.create_table(
        "raw_storage_objects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("source_system_id", sa.Uuid(), nullable=False),
        sa.Column("ingestion_batch_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("object_number", sa.String(length=120), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("object_type", sa.String(length=40), nullable=False),
        sa.Column("storage_provider", sa.String(length=40), nullable=False),
        sa.Column("storage_reference", sa.String(length=1000), nullable=False),
        sa.Column("storage_container_reference", sa.String(length=500), nullable=True),
        sa.Column("storage_region", sa.String(length=100), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("normalized_filename", sa.String(length=255), nullable=True),
        sa.Column("file_extension", sa.String(length=30), nullable=True),
        sa.Column("media_type", sa.String(length=150), nullable=True),
        sa.Column("encoding", sa.String(length=50), nullable=True),
        sa.Column("compression_type", sa.String(length=30), nullable=False),
        sa.Column("content_checksum_algorithm", sa.String(length=20), nullable=False),
        sa.Column("content_checksum", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("column_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("integrity_status", sa.String(length=30), nullable=False),
        sa.Column("retention_class", sa.String(length=30), nullable=False),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legal_hold", sa.Boolean(), nullable=False),
        sa.Column("legal_hold_reason", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_raw_object_id", sa.Uuid(), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "compression_type IN ('none', 'gzip', 'zip', 'tar', 'tar_gzip', 'bz2', 'xz', 'custom')",
            name="ck_raw_compression",
        ),
        sa.CheckConstraint(
            "content_checksum_algorithm IN ('sha256', 'sha512', 'md5')",
            name="ck_raw_checksum_algorithm",
        ),
        sa.CheckConstraint(
            "integrity_status IN ('unknown', 'pending', 'verified', 'mismatch', 'corrupted', 'unavailable')",
            name="ck_raw_integrity_status",
        ),
        sa.CheckConstraint(
            "object_type IN ('file', 'api_payload', 'database_extract', 'message', 'email', 'email_attachment', 'document', 'archive', 'stream_partition', 'telemetry_bundle', 'simulated_file', 'custom')",
            name="ck_raw_object_type",
        ),
        sa.CheckConstraint(
            "retention_class IN ('transient', 'standard', 'extended', 'regulatory', 'permanent', 'custom')",
            name="ck_raw_retention_class",
        ),
        sa.CheckConstraint(
            "status != 'sealed' OR sealed_at IS NOT NULL", name="ck_raw_sealed_timestamp"
        ),
        sa.CheckConstraint(
            "status IN ('registered', 'receiving', 'received', 'verifying', 'sealed', 'quarantined', 'superseded', 'archived', 'deletion_requested', 'deleted_reference')",
            name="ck_raw_status",
        ),
        sa.CheckConstraint(
            "storage_provider IN ('local', 's3', 'azure_blob', 'google_cloud_storage', 'supabase_storage', 'database_reference', 'external_managed', 'custom')",
            name="ck_raw_storage_provider",
        ),
        sa.CheckConstraint(
            "size_bytes >= 0 AND (record_count IS NULL OR record_count >= 0) AND (column_count IS NULL OR column_count >= 0)",
            name="ck_raw_counts_nonnegative",
        ),
        sa.CheckConstraint(
            "supersedes_raw_object_id IS NULL OR supersedes_raw_object_id != id",
            name="ck_raw_not_self_superseding",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_batch_id"], ["ingestion_batches.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_system_id"], ["source_systems.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["supersedes_raw_object_id"], ["raw_storage_objects.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_raw_objects_organization_idempotency"
        ),
        sa.UniqueConstraint(
            "organization_id", "object_number", name="uq_raw_objects_organization_number"
        ),
    )
    op.create_index(
        "ix_raw_objects_content_checksum", "raw_storage_objects", ["content_checksum"], unique=False
    )
    op.create_index(
        "ix_raw_objects_dataset_version_id",
        "raw_storage_objects",
        ["dataset_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_raw_objects_ingestion_batch_id",
        "raw_storage_objects",
        ["ingestion_batch_id"],
        unique=False,
    )
    op.create_index(
        "ix_raw_objects_integrity_status", "raw_storage_objects", ["integrity_status"], unique=False
    )
    op.create_index(
        "ix_raw_objects_legal_hold", "raw_storage_objects", ["legal_hold"], unique=False
    )
    op.create_index(
        "ix_raw_objects_organization_id", "raw_storage_objects", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_raw_objects_received_at", "raw_storage_objects", ["received_at"], unique=False
    )
    op.create_index(
        "ix_raw_objects_retention_until", "raw_storage_objects", ["retention_until"], unique=False
    )
    op.create_index(
        "ix_raw_objects_source_system_id", "raw_storage_objects", ["source_system_id"], unique=False
    )
    op.create_index("ix_raw_objects_status", "raw_storage_objects", ["status"], unique=False)
    op.create_table(
        "lineage_edges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("from_node_id", sa.Uuid(), nullable=False),
        sa.Column("to_node_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_type", sa.String(length=40), nullable=False),
        sa.Column("processing_run_id", sa.Uuid(), nullable=True),
        sa.Column("processing_run_key", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "relationship_type IN ('originates_from', 'delivered_in', 'describes', 'stored_as', 'contains', 'extracted_from', 'parsed_from', 'derived_from', 'transformed_from', 'validated_against', 'supersedes', 'produced_by', 'consumed_by', 'linked_to', 'custom')",
            name="ck_lineage_edge_relationship",
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_lineage_edge_confidence",
        ),
        sa.CheckConstraint("from_node_id != to_node_id", name="ck_lineage_edge_not_self"),
        sa.CheckConstraint("sequence >= 0", name="ck_lineage_edge_sequence_nonnegative"),
        sa.ForeignKeyConstraint(["from_node_id"], ["lineage_nodes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["processing_run_id"], ["processing_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["to_node_id"], ["lineage_nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "from_node_id",
            "to_node_id",
            "relationship_type",
            "processing_run_key",
            name="uq_lineage_edge_identity",
        ),
    )
    op.create_index(
        "ix_lineage_edges_from_node_id", "lineage_edges", ["from_node_id"], unique=False
    )
    op.create_index(
        "ix_lineage_edges_organization_id", "lineage_edges", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_lineage_edges_processing_run_id", "lineage_edges", ["processing_run_id"], unique=False
    )
    op.create_index(
        "ix_lineage_edges_relationship_type", "lineage_edges", ["relationship_type"], unique=False
    )
    op.create_index("ix_lineage_edges_to_node_id", "lineage_edges", ["to_node_id"], unique=False)
    op.create_table(
        "lineage_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("processing_run_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=30), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('user', 'service', 'system')", name="ck_lineage_event_actor_type"
        ),
        sa.CheckConstraint(
            "event_type IN ('registered', 'received', 'checksum_verified', 'integrity_mismatch', 'sealed', 'quarantined', 'superseded', 'archived', 'deletion_requested', 'reference_deleted', 'lineage_link_created', 'processing_started', 'processing_completed', 'processing_failed', 'legal_hold_applied', 'legal_hold_released', 'custom')",
            name="ck_lineage_event_type",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["processing_run_id"], ["processing_runs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_lineage_events_entity", "lineage_events", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        "ix_lineage_events_occurred_at", "lineage_events", ["occurred_at"], unique=False
    )
    op.create_index(
        "ix_lineage_events_organization_id", "lineage_events", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_lineage_events_processing_run_id", "lineage_events", ["processing_run_id"], unique=False
    )
    op.create_table(
        "raw_record_references",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("raw_storage_object_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("record_sequence", sa.Integer(), nullable=False),
        sa.Column("record_locator", sa.String(length=500), nullable=True),
        sa.Column("record_key", sa.String(length=255), nullable=True),
        sa.Column("record_checksum_algorithm", sa.String(length=20), nullable=True),
        sa.Column("record_checksum", sa.String(length=128), nullable=True),
        sa.Column("source_row_number", sa.Integer(), nullable=True),
        sa.Column("source_sheet_name", sa.String(length=150), nullable=True),
        sa.Column("source_page_number", sa.Integer(), nullable=True),
        sa.Column("source_message_id", sa.String(length=255), nullable=True),
        sa.Column("source_event_id", sa.String(length=255), nullable=True),
        sa.Column("source_partition", sa.String(length=100), nullable=True),
        sa.Column("source_offset", sa.String(length=100), nullable=True),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "record_checksum_algorithm IS NULL OR record_checksum_algorithm IN ('sha256', 'sha512', 'md5')",
            name="ck_raw_record_checksum_algorithm",
        ),
        sa.CheckConstraint(
            "status IN ('registered', 'available', 'excluded', 'quarantined', 'superseded', 'unavailable')",
            name="ck_raw_record_status",
        ),
        sa.CheckConstraint("record_sequence > 0", name="ck_raw_record_sequence_positive"),
        sa.CheckConstraint(
            "source_page_number IS NULL OR source_page_number > 0",
            name="ck_raw_record_page_positive",
        ),
        sa.CheckConstraint(
            "source_row_number IS NULL OR source_row_number > 0", name="ck_raw_record_row_positive"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["raw_storage_object_id"], ["raw_storage_objects.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "raw_storage_object_id", "record_sequence", name="uq_raw_records_object_sequence"
        ),
    )
    op.create_index(
        "ix_raw_records_dataset_version_id",
        "raw_record_references",
        ["dataset_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_raw_records_object_id", "raw_record_references", ["raw_storage_object_id"], unique=False
    )
    op.create_index(
        "ix_raw_records_organization_id", "raw_record_references", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_raw_records_record_key", "raw_record_references", ["record_key"], unique=False
    )
    op.create_index(
        "ix_raw_records_source_event_id", "raw_record_references", ["source_event_id"], unique=False
    )
    op.create_index(
        "ix_raw_records_source_timestamp",
        "raw_record_references",
        ["source_timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_raw_records_source_timestamp", table_name="raw_record_references")
    op.drop_index("ix_raw_records_source_event_id", table_name="raw_record_references")
    op.drop_index("ix_raw_records_record_key", table_name="raw_record_references")
    op.drop_index("ix_raw_records_organization_id", table_name="raw_record_references")
    op.drop_index("ix_raw_records_object_id", table_name="raw_record_references")
    op.drop_index("ix_raw_records_dataset_version_id", table_name="raw_record_references")
    op.drop_table("raw_record_references")
    op.drop_index("ix_lineage_events_processing_run_id", table_name="lineage_events")
    op.drop_index("ix_lineage_events_organization_id", table_name="lineage_events")
    op.drop_index("ix_lineage_events_occurred_at", table_name="lineage_events")
    op.drop_index("ix_lineage_events_entity", table_name="lineage_events")
    op.drop_table("lineage_events")
    op.drop_index("ix_lineage_edges_to_node_id", table_name="lineage_edges")
    op.drop_index("ix_lineage_edges_relationship_type", table_name="lineage_edges")
    op.drop_index("ix_lineage_edges_processing_run_id", table_name="lineage_edges")
    op.drop_index("ix_lineage_edges_organization_id", table_name="lineage_edges")
    op.drop_index("ix_lineage_edges_from_node_id", table_name="lineage_edges")
    op.drop_table("lineage_edges")
    op.drop_index("ix_raw_objects_status", table_name="raw_storage_objects")
    op.drop_index("ix_raw_objects_source_system_id", table_name="raw_storage_objects")
    op.drop_index("ix_raw_objects_retention_until", table_name="raw_storage_objects")
    op.drop_index("ix_raw_objects_received_at", table_name="raw_storage_objects")
    op.drop_index("ix_raw_objects_organization_id", table_name="raw_storage_objects")
    op.drop_index("ix_raw_objects_legal_hold", table_name="raw_storage_objects")
    op.drop_index("ix_raw_objects_integrity_status", table_name="raw_storage_objects")
    op.drop_index("ix_raw_objects_ingestion_batch_id", table_name="raw_storage_objects")
    op.drop_index("ix_raw_objects_dataset_version_id", table_name="raw_storage_objects")
    op.drop_index("ix_raw_objects_content_checksum", table_name="raw_storage_objects")
    op.drop_table("raw_storage_objects")
    op.drop_index("ix_processing_runs_status", table_name="processing_runs")
    op.drop_index("ix_processing_runs_run_type", table_name="processing_runs")
    op.drop_index("ix_processing_runs_organization_id", table_name="processing_runs")
    op.drop_index("ix_processing_runs_dataset_version_id", table_name="processing_runs")
    op.drop_index("ix_processing_runs_correlation_id", table_name="processing_runs")
    op.drop_index("ix_processing_runs_batch_id", table_name="processing_runs")
    op.drop_table("processing_runs")
    op.drop_index("ix_lineage_nodes_organization_id", table_name="lineage_nodes")
    op.drop_index("ix_lineage_nodes_node_type", table_name="lineage_nodes")
    op.drop_index("ix_lineage_nodes_entity_id", table_name="lineage_nodes")
    op.drop_table("lineage_nodes")
    # ### end Alembic commands ###
