# ruff: noqa: E501
"""shared trust engine foundation

Revision ID: 20260724_0006
Revises: 20260724_0005
Create Date: 2026-07-24 19:29:36.355387
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260724_0006"
down_revision: str | None = "20260724_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trust_assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("ingestion_batch_id", sa.Uuid(), nullable=True),
        sa.Column("industry_pack_code", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("completeness_score", sa.Float(), nullable=True),
        sa.Column("validity_score", sa.Float(), nullable=True),
        sa.Column("consistency_score", sa.Float(), nullable=True),
        sa.Column("uniqueness_score", sa.Float(), nullable=True),
        sa.Column("timeliness_score", sa.Float(), nullable=True),
        sa.Column("lineage_score", sa.Float(), nullable=True),
        sa.Column("assessed_row_count", sa.Integer(), nullable=False),
        sa.Column("passed_rule_count", sa.Integer(), nullable=False),
        sa.Column("warning_rule_count", sa.Integer(), nullable=False),
        sa.Column("failed_rule_count", sa.Integer(), nullable=False),
        sa.Column("skipped_rule_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'completed_with_warnings', 'failed', 'cancelled')",
            name="ck_trust_assessment_status",
        ),
        sa.CheckConstraint(
            "(completeness_score IS NULL OR (completeness_score >= 0 AND completeness_score <= 100)) AND (validity_score IS NULL OR (validity_score >= 0 AND validity_score <= 100)) AND (consistency_score IS NULL OR (consistency_score >= 0 AND consistency_score <= 100)) AND (uniqueness_score IS NULL OR (uniqueness_score >= 0 AND uniqueness_score <= 100)) AND (timeliness_score IS NULL OR (timeliness_score >= 0 AND timeliness_score <= 100)) AND (lineage_score IS NULL OR (lineage_score >= 0 AND lineage_score <= 100))",
            name="ck_trust_assessment_dimension_scores",
        ),
        sa.CheckConstraint(
            "assessed_row_count >= 0 AND passed_rule_count >= 0 AND warning_rule_count >= 0 AND failed_rule_count >= 0 AND skipped_rule_count >= 0",
            name="ck_trust_assessment_counts",
        ),
        sa.CheckConstraint(
            "overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 100)",
            name="ck_trust_assessment_overall_score",
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["ingestion_batch_id"], ["ingestion_batches.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_trust_assessments_batch_id", "trust_assessments", ["ingestion_batch_id"], unique=False
    )
    op.create_index(
        "ix_trust_assessments_created_at", "trust_assessments", ["created_at"], unique=False
    )
    op.create_index(
        "ix_trust_assessments_dataset_id", "trust_assessments", ["dataset_id"], unique=False
    )
    op.create_index(
        "ix_trust_assessments_organization_id",
        "trust_assessments",
        ["organization_id"],
        unique=False,
    )
    op.create_index("ix_trust_assessments_status", "trust_assessments", ["status"], unique=False)
    op.create_table(
        "analytical_readiness_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("trust_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("analytical_level", sa.String(length=40), nullable=False),
        sa.Column("readiness_status", sa.String(length=40), nullable=False),
        sa.Column(
            "blocking_rule_codes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "warning_rule_codes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "analytical_level IN ('arithmetic', 'statistical', 'predictive', 'optimization', 'economic_recovery')",
            name="ck_readiness_level",
        ),
        sa.CheckConstraint(
            "readiness_status IN ('ready', 'ready_with_warnings', 'insufficient_data', 'blocked')",
            name="ck_readiness_status",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["trust_assessment_id"], ["trust_assessments.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_readiness_assessment_id",
        "analytical_readiness_decisions",
        ["trust_assessment_id"],
        unique=False,
    )
    op.create_index(
        "ix_readiness_created_at", "analytical_readiness_decisions", ["created_at"], unique=False
    )
    op.create_index(
        "ix_readiness_organization_id",
        "analytical_readiness_decisions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_readiness_status", "analytical_readiness_decisions", ["readiness_status"], unique=False
    )
    op.create_table(
        "trust_rule_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("trust_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("rule_code", sa.String(length=100), nullable=False),
        sa.Column("rule_version", sa.String(length=30), nullable=False),
        sa.Column("rule_name", sa.String(length=200), nullable=False),
        sa.Column("dimension", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("execution_status", sa.String(length=20), nullable=False),
        sa.Column("result_status", sa.String(length=30), nullable=False),
        sa.Column("checked_record_count", sa.Integer(), nullable=False),
        sa.Column("affected_record_count", sa.Integer(), nullable=False),
        sa.Column("affected_percentage", sa.Float(), nullable=True),
        sa.Column(
            "threshold_definition",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "observed_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("remediation_guidance", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "dimension IN ('completeness', 'validity', 'consistency', 'uniqueness', 'timeliness', 'lineage', 'referential_integrity')",
            name="ck_trust_rule_dimension",
        ),
        sa.CheckConstraint(
            "execution_status IN ('pending', 'running', 'completed', 'errored')",
            name="ck_trust_rule_execution_status",
        ),
        sa.CheckConstraint(
            "result_status IN ('passed', 'warning', 'failed', 'skipped', 'not_applicable')",
            name="ck_trust_rule_result_status",
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'error', 'critical')", name="ck_trust_rule_severity"
        ),
        sa.CheckConstraint(
            "affected_percentage IS NULL OR (affected_percentage >= 0 AND affected_percentage <= 100)",
            name="ck_trust_rule_affected_percentage",
        ),
        sa.CheckConstraint(
            "checked_record_count >= 0 AND affected_record_count >= 0", name="ck_trust_rule_counts"
        ),
        sa.CheckConstraint(
            "score IS NULL OR (score >= 0 AND score <= 100)", name="ck_trust_rule_score"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["trust_assessment_id"], ["trust_assessments.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_trust_rule_results_assessment_id",
        "trust_rule_results",
        ["trust_assessment_id"],
        unique=False,
    )
    op.create_index(
        "ix_trust_rule_results_created_at", "trust_rule_results", ["created_at"], unique=False
    )
    op.create_index(
        "ix_trust_rule_results_organization_id",
        "trust_rule_results",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_trust_rule_results_result_status", "trust_rule_results", ["result_status"], unique=False
    )
    op.create_index(
        "ix_trust_rule_results_rule_code", "trust_rule_results", ["rule_code"], unique=False
    )
    op.create_table(
        "trust_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("trust_rule_result_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("source_record_identifier", sa.String(length=255), nullable=True),
        sa.Column("canonical_record_identifier", sa.String(length=255), nullable=True),
        sa.Column("field_name", sa.String(length=150), nullable=True),
        sa.Column(
            "observed_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("expected_condition", sa.Text(), nullable=True),
        sa.Column("evidence_type", sa.String(length=30), nullable=False),
        sa.Column("source_reference", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "evidence_type IN ('record', 'field', 'duplicate', 'reference', 'schema', 'lineage', 'summary')",
            name="ck_trust_evidence_type",
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["trust_rule_result_id"], ["trust_rule_results.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_trust_evidence_created_at", "trust_evidence", ["created_at"], unique=False)
    op.create_index("ix_trust_evidence_dataset_id", "trust_evidence", ["dataset_id"], unique=False)
    op.create_index(
        "ix_trust_evidence_organization_id", "trust_evidence", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_trust_evidence_rule_result_id", "trust_evidence", ["trust_rule_result_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trust_evidence_rule_result_id", table_name="trust_evidence")
    op.drop_index("ix_trust_evidence_organization_id", table_name="trust_evidence")
    op.drop_index("ix_trust_evidence_dataset_id", table_name="trust_evidence")
    op.drop_index("ix_trust_evidence_created_at", table_name="trust_evidence")
    op.drop_table("trust_evidence")
    op.drop_index("ix_trust_rule_results_rule_code", table_name="trust_rule_results")
    op.drop_index("ix_trust_rule_results_result_status", table_name="trust_rule_results")
    op.drop_index("ix_trust_rule_results_organization_id", table_name="trust_rule_results")
    op.drop_index("ix_trust_rule_results_created_at", table_name="trust_rule_results")
    op.drop_index("ix_trust_rule_results_assessment_id", table_name="trust_rule_results")
    op.drop_table("trust_rule_results")
    op.drop_index("ix_readiness_status", table_name="analytical_readiness_decisions")
    op.drop_index("ix_readiness_organization_id", table_name="analytical_readiness_decisions")
    op.drop_index("ix_readiness_created_at", table_name="analytical_readiness_decisions")
    op.drop_index("ix_readiness_assessment_id", table_name="analytical_readiness_decisions")
    op.drop_table("analytical_readiness_decisions")
    op.drop_index("ix_trust_assessments_status", table_name="trust_assessments")
    op.drop_index("ix_trust_assessments_organization_id", table_name="trust_assessments")
    op.drop_index("ix_trust_assessments_dataset_id", table_name="trust_assessments")
    op.drop_index("ix_trust_assessments_created_at", table_name="trust_assessments")
    op.drop_index("ix_trust_assessments_batch_id", table_name="trust_assessments")
    op.drop_table("trust_assessments")
    # ### end Alembic commands ###
