"""P3.xxD.1E holistic validation ontology

Revision ID: 20260828_0053
Revises: 20260828_0052
Create Date: 2026-08-28 10:48:30.330168
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260828_0053"
down_revision: str | None = "20260828_0052"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "validation_causal_truths",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("ground_truth_id", sa.Uuid(), nullable=False),
        sa.Column("truth_causal_id", sa.String(length=100), nullable=False),
        sa.Column("linked_leakage_id", sa.String(length=100), nullable=True),
        sa.Column("linked_finding_id", sa.String(length=100), nullable=True),
        sa.Column("scenario_code", sa.String(length=100), nullable=True),
        sa.Column("expected_root_cause", sa.Text(), nullable=True),
        sa.Column(
            "expected_causal_chain",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ground_truth_id"], ["validation_ground_truths.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_validation_causal_truths_org",
        "validation_causal_truths",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "validation_data_quality_truths",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("ground_truth_id", sa.Uuid(), nullable=False),
        sa.Column("truth_dq_id", sa.String(length=100), nullable=False),
        sa.Column("dq_family", sa.String(length=100), nullable=True),
        sa.Column("affected_record", sa.String(length=200), nullable=True),
        sa.Column("affected_dataset_or_field", sa.String(length=200), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=50), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ground_truth_id"], ["validation_ground_truths.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ground_truth_id", "truth_dq_id", name="uq_validation_dq_truth_id"),
    )
    op.create_index(
        "ix_validation_dq_truths_org",
        "validation_data_quality_truths",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "validation_ground_truth_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("ground_truth_id", sa.Uuid(), nullable=False),
        sa.Column("declared_role", sa.String(length=50), nullable=True),
        sa.Column("detected_role", sa.String(length=50), nullable=True),
        sa.Column("storage_reference", sa.String(length=500), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ground_truth_id"], ["validation_ground_truths.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_validation_gt_documents_gt",
        "validation_ground_truth_documents",
        ["ground_truth_id"],
        unique=False,
    )
    op.create_table(
        "validation_leakage_truths",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("ground_truth_id", sa.Uuid(), nullable=False),
        sa.Column("truth_leakage_id", sa.String(length=100), nullable=False),
        sa.Column("scenario_code", sa.String(length=100), nullable=True),
        sa.Column("business_context", sa.String(length=200), nullable=True),
        sa.Column(
            "affected_records",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "entities",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "time_window",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column(
            "causal_chain",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("severity", sa.String(length=50), nullable=True),
        sa.Column("recoverable", sa.Boolean(), nullable=True),
        sa.Column("detection_family", sa.String(length=100), nullable=True),
        sa.Column(
            "expected_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("true_leakage_value", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("recoverable_value", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ground_truth_id"], ["validation_ground_truths.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ground_truth_id", "truth_leakage_id", name="uq_validation_leakage_truth_id"
        ),
    )
    op.create_index(
        "ix_validation_leakage_truths_org",
        "validation_leakage_truths",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "validation_package_integrity_issues",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("ground_truth_id", sa.Uuid(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("document_role", sa.String(length=50), nullable=True),
        sa.Column("truth_ref", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "severity IN ('warning', 'error')", name="ck_validation_integrity_severity"
        ),
        sa.ForeignKeyConstraint(
            ["ground_truth_id"], ["validation_ground_truths.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_validation_integrity_issues_gt",
        "validation_package_integrity_issues",
        ["ground_truth_id"],
        unique=False,
    )
    op.create_table(
        "validation_dimension_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("validation_run_id", sa.Uuid(), nullable=False),
        sa.Column("dimension_code", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["validation_run_id"], ["simulation_validation_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "validation_run_id", "dimension_code", name="uq_validation_dimension_result"
        ),
    )
    op.create_index(
        "ix_validation_dimension_results_run",
        "validation_dimension_results",
        ["validation_run_id"],
        unique=False,
    )
    op.add_column(
        "validation_expected_findings",
        sa.Column("expected_detection_family", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "validation_expected_findings",
        sa.Column("linked_leakage_id", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "validation_expected_findings",
        sa.Column(
            "affected_records",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    # batch mode: SQLite has no ALTER COLUMN, only table recreation --
    # this is a no-op wrapper on Postgres, required for SQLite.
    with op.batch_alter_table("validation_expected_findings") as batch:
        batch.alter_column(
            "domain",
            existing_type=sa.VARCHAR(length=100),
            nullable=True,
        )
    op.add_column(
        "validation_finding_matches",
        sa.Column(
            "dimension_code",
            sa.String(length=30),
            nullable=False,
            # Backfills every pre-P3.xxD.1E row -- every match ever
            # persisted before this migration was a finding_detection
            # match, since no other dimension existed yet.
            server_default="finding_detection",
        ),
    )
    op.add_column(
        "validation_finding_matches",
        sa.Column("expected_leakage_truth_id", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "validation_finding_matches",
        sa.Column(
            "matched_dimensions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.add_column(
        "validation_finding_matches",
        sa.Column(
            "unmatched_dimensions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.add_column("validation_finding_matches", sa.Column("reason", sa.Text(), nullable=True))
    # batch mode: SQLite has no ALTER TABLE ADD CONSTRAINT.
    with op.batch_alter_table("validation_finding_matches") as batch:
        batch.create_foreign_key(
            "fk_validation_finding_matches_leakage_truth",
            "validation_leakage_truths",
            ["expected_leakage_truth_id"],
            ["id"],
            ondelete="RESTRICT",
        )
    op.add_column(
        "validation_ground_truths", sa.Column("adapter_code", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "validation_ground_truths",
        sa.Column("adapter_version", sa.String(length=30), nullable=True),
    )
    op.add_column(
        "validation_ground_truths",
        sa.Column(
            "schema_version",
            sa.String(length=50),
            nullable=False,
            # Backfills every pre-P3.xxD.1E row (all of which really were
            # uploaded through the V1 simple adapter, since no other
            # adapter existed yet) without a table rewrite; dropped
            # immediately after so new rows are never silently defaulted
            # -- the ORM's own Python-side default is authoritative for
            # inserts going forward.
            server_default="intel4ops_simple_v1",
        ),
    )
    # Deliberately no "drop server_default" step here: the SQL-level
    # default matches the ORM's own Python-side default exactly, so
    # leaving it in place is harmless (and avoids an SQLite-incompatible
    # bare ALTER COLUMN -- see the batch_alter_table note above).
    op.add_column(
        "validation_ground_truths",
        sa.Column(
            "manifest_summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###

    # Not auto-detected: autogenerate diffs constraint presence by name,
    # never CHECK constraint body text, so the widened "has a side"
    # condition (a leakage-value match now counts too) needs to be done
    # by hand. batch mode: SQLite has no ALTER/DROP CONSTRAINT at all.
    with op.batch_alter_table("validation_finding_matches") as batch:
        batch.drop_constraint("ck_validation_finding_match_has_side", type_="check")
        batch.create_check_constraint(
            "ck_validation_finding_match_has_side",
            "expected_finding_id IS NOT NULL OR actual_finding_id IS NOT NULL "
            "OR expected_leakage_truth_id IS NOT NULL",
        )


def downgrade() -> None:
    # Reverses the hand-written CHECK constraint widening and FK addition
    # above, in one pass -- must happen before expected_leakage_truth_id
    # is dropped below. batch mode: SQLite has no ALTER/DROP CONSTRAINT at
    # all.
    with op.batch_alter_table("validation_finding_matches") as batch:
        batch.drop_constraint("ck_validation_finding_match_has_side", type_="check")
        batch.create_check_constraint(
            "ck_validation_finding_match_has_side",
            "expected_finding_id IS NOT NULL OR actual_finding_id IS NOT NULL",
        )
        batch.drop_constraint("fk_validation_finding_matches_leakage_truth", type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("validation_ground_truths", "manifest_summary")
    op.drop_column("validation_ground_truths", "schema_version")
    op.drop_column("validation_ground_truths", "adapter_version")
    op.drop_column("validation_ground_truths", "adapter_code")
    op.drop_column("validation_finding_matches", "reason")
    op.drop_column("validation_finding_matches", "unmatched_dimensions")
    op.drop_column("validation_finding_matches", "matched_dimensions")
    op.drop_column("validation_finding_matches", "expected_leakage_truth_id")
    op.drop_column("validation_finding_matches", "dimension_code")
    with op.batch_alter_table("validation_expected_findings") as batch:
        batch.alter_column(
            "domain",
            existing_type=sa.VARCHAR(length=100),
            nullable=False,
        )
    op.drop_column("validation_expected_findings", "affected_records")
    op.drop_column("validation_expected_findings", "linked_leakage_id")
    op.drop_column("validation_expected_findings", "expected_detection_family")
    op.drop_index("ix_validation_dimension_results_run", table_name="validation_dimension_results")
    op.drop_table("validation_dimension_results")
    op.drop_index(
        "ix_validation_integrity_issues_gt", table_name="validation_package_integrity_issues"
    )
    op.drop_table("validation_package_integrity_issues")
    op.drop_index("ix_validation_leakage_truths_org", table_name="validation_leakage_truths")
    op.drop_table("validation_leakage_truths")
    op.drop_index("ix_validation_gt_documents_gt", table_name="validation_ground_truth_documents")
    op.drop_table("validation_ground_truth_documents")
    op.drop_index("ix_validation_dq_truths_org", table_name="validation_data_quality_truths")
    op.drop_table("validation_data_quality_truths")
    op.drop_index("ix_validation_causal_truths_org", table_name="validation_causal_truths")
    op.drop_table("validation_causal_truths")
    # ### end Alembic commands ###
