"""Canonical mapping and causal-ready data foundation.

Revision ID: 20260804_0031
Revises: 20260802_0030
Create Date: 2026-08-04 09:45:42.902097
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import context, op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "20260804_0031"
down_revision: str | None = "20260802_0030"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

LINEAGE_NODE_VALUES = (
    "'source_system','ingestion_batch','dataset','dataset_version',"
    "'raw_storage_object','raw_record_reference','processing_run','source_schema',"
    "'mapping_run','mapping_record_result','canonical_entity','canonical_event',"
    "'canonical_metric','custom'"
)
LEGACY_LINEAGE_NODE_VALUES = (
    "'source_system','ingestion_batch','dataset','dataset_version',"
    "'raw_storage_object','raw_record_reference','processing_run','custom'"
)
LINEAGE_RELATIONSHIP_VALUES = (
    "'originates_from','delivered_in','describes','stored_as','contains','extracted_from',"
    "'parsed_from','derived_from','transformed_from','validated_against','supersedes',"
    "'produced_by','consumed_by','mapped_by','canonicalized_as','resolved_to','linked_to','custom'"
)
LEGACY_LINEAGE_RELATIONSHIP_VALUES = (
    "'originates_from','delivered_in','describes','stored_as','contains','extracted_from',"
    "'parsed_from','derived_from','transformed_from','validated_against','supersedes',"
    "'produced_by','consumed_by','linked_to','custom'"
)


def _assert_clean_raw_record_parent_keys() -> None:
    duplicates = op.get_bind().scalar(
        sa.text(
            """
            SELECT count(*)
            FROM (
                SELECT organization_id, id
                FROM raw_record_references
                GROUP BY organization_id, id
                HAVING count(*) > 1
            ) AS duplicate_targets
            """
        )
    )
    if duplicates:
        raise RuntimeError(
            "uq_raw_record_references_org_id precondition failed with "
            f"{duplicates} duplicate targets"
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not context.is_offline_mode():
        _assert_clean_raw_record_parent_keys()

    with op.batch_alter_table("raw_record_references") as batch_op:
        batch_op.create_unique_constraint(
            "uq_raw_record_references_org_id",
            ["organization_id", "id"],
        )

    with op.batch_alter_table("lineage_nodes") as batch_op:
        batch_op.drop_constraint("ck_lineage_node_type", type_="check")
        batch_op.create_check_constraint(
            "ck_lineage_node_type",
            f"node_type IN ({LINEAGE_NODE_VALUES})",
        )

    with op.batch_alter_table("lineage_edges") as batch_op:
        batch_op.drop_constraint("ck_lineage_edge_relationship", type_="check")
        batch_op.create_check_constraint(
            "ck_lineage_edge_relationship",
            f"relationship_type IN ({LINEAGE_RELATIONSHIP_VALUES})",
        )

    op.create_table(
        "canonical_field_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_type_kind", sa.String(length=20), nullable=False),
        sa.Column("canonical_type_id", sa.Uuid(), nullable=False),
        sa.Column("field_code", sa.String(length=150), nullable=False),
        sa.Column("display_name", sa.String(length=250), nullable=False),
        sa.Column("data_type", sa.String(length=30), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("unit_dimension", sa.String(length=80), nullable=True),
        sa.Column(
            "allowed_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "validation_rule",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "canonical_type_kind IN ('entity', 'event', 'metric')",
            name="ck_canonical_field_type_kind",
        ),
        sa.CheckConstraint(
            "data_type IN ('string', 'integer', 'decimal', 'boolean', 'datetime', 'date', 'uuid', 'enum')",
            name="ck_canonical_field_data_type",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "canonical_type_kind",
            "canonical_type_id",
            "field_code",
            name="uq_canonical_field_type_code",
        ),
    )
    op.create_index(
        "ix_canonical_field_type",
        "canonical_field_definitions",
        ["canonical_type_kind", "canonical_type_id"],
        unique=False,
    )
    op.create_table(
        "canonical_entity_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type_code", sa.String(length=150), nullable=False),
        sa.Column("display_name", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("industry_pack_code", sa.String(length=100), nullable=True),
        sa.Column("identity_strategy_code", sa.String(length=100), nullable=True),
        sa.Column("owner_organization_id", sa.Uuid(), nullable=True),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_key", sa.String(length=180), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "scope_type IN ('shared_core','industry','regional','organization') AND ((scope_type = 'organization' AND owner_organization_id IS NOT NULL) OR (scope_type <> 'organization'))",
            name="ck_canonical_entity_type_scope",
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type_code", "scope_key", name="uq_canonical_entity_type_scope"),
    )
    op.create_index(
        "ix_canonical_entity_type_code", "canonical_entity_types", ["type_code"], unique=False
    )
    op.create_index(
        "ix_canonical_entity_type_owner",
        "canonical_entity_types",
        ["owner_organization_id"],
        unique=False,
    )
    op.create_table(
        "canonical_metric_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type_code", sa.String(length=150), nullable=False),
        sa.Column("display_name", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("industry_pack_code", sa.String(length=100), nullable=True),
        sa.Column("unit_dimension", sa.String(length=80), nullable=True),
        sa.Column("default_unit", sa.String(length=40), nullable=True),
        sa.Column("aggregation_hint", sa.String(length=30), nullable=False),
        sa.Column("owner_organization_id", sa.Uuid(), nullable=True),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_key", sa.String(length=180), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "aggregation_hint IN ('sum', 'average', 'last_value', 'max', 'min', 'count')",
            name="ck_canonical_metric_type_aggregation",
        ),
        sa.CheckConstraint(
            "scope_type IN ('shared_core','industry','regional','organization') AND ((scope_type = 'organization' AND owner_organization_id IS NOT NULL) OR (scope_type <> 'organization'))",
            name="ck_canonical_metric_type_scope",
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type_code", "scope_key", name="uq_canonical_metric_type_scope"),
    )
    op.create_index(
        "ix_canonical_metric_type_code", "canonical_metric_types", ["type_code"], unique=False
    )
    op.create_index(
        "ix_canonical_metric_type_owner",
        "canonical_metric_types",
        ["owner_organization_id"],
        unique=False,
    )
    op.create_table(
        "mapping_audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("actor_type", sa.String(length=30), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_mapping_audit_entity",
        "mapping_audit_events",
        ["organization_id", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_mapping_audit_org_time",
        "mapping_audit_events",
        ["organization_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "mapping_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_code", sa.String(length=150), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("industry_pack_code", sa.String(length=100), nullable=True),
        sa.Column("source_system_type", sa.String(length=100), nullable=True),
        sa.Column("target_canonical_type_kind", sa.String(length=20), nullable=False),
        sa.Column("target_canonical_type_id", sa.Uuid(), nullable=False),
        sa.Column("owner_organization_id", sa.Uuid(), nullable=True),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_key", sa.String(length=180), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "scope_type IN ('shared_core','industry','regional','organization') AND ((scope_type = 'organization' AND owner_organization_id IS NOT NULL) OR (scope_type <> 'organization'))",
            name="ck_mapping_template_scope",
        ),
        sa.CheckConstraint(
            "target_canonical_type_kind IN ('entity', 'event', 'metric')",
            name="ck_mapping_template_target_kind",
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("template_code", "scope_key", name="uq_mapping_template_scope"),
    )
    op.create_index(
        "ix_mapping_template_code", "mapping_templates", ["template_code"], unique=False
    )
    op.create_index(
        "ix_mapping_template_industry", "mapping_templates", ["industry_pack_code"], unique=False
    )
    op.create_index(
        "ix_mapping_template_owner", "mapping_templates", ["owner_organization_id"], unique=False
    )
    op.create_table(
        "value_crosswalks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("crosswalk_code", sa.String(length=150), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("canonical_field_definition_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("owner_organization_id", sa.Uuid(), nullable=True),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_key", sa.String(length=180), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "scope_type IN ('shared_core','industry','regional','organization') AND ((scope_type = 'organization' AND owner_organization_id IS NOT NULL) OR (scope_type <> 'organization'))",
            name="ck_value_crosswalk_scope",
        ),
        sa.ForeignKeyConstraint(
            ["canonical_field_definition_id"],
            ["canonical_field_definitions.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crosswalk_code", "scope_key", name="uq_value_crosswalk_scope"),
        sa.UniqueConstraint("owner_organization_id", "id", name="uq_value_crosswalk_owner_id"),
    )
    op.create_index("ix_value_crosswalk_code", "value_crosswalks", ["crosswalk_code"], unique=False)
    op.create_index(
        "ix_value_crosswalk_owner", "value_crosswalks", ["owner_organization_id"], unique=False
    )
    op.create_table(
        "canonical_event_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type_code", sa.String(length=150), nullable=False),
        sa.Column("display_name", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("industry_pack_code", sa.String(length=100), nullable=True),
        sa.Column("applicable_entity_type_id", sa.Uuid(), nullable=True),
        sa.Column("owner_organization_id", sa.Uuid(), nullable=True),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_key", sa.String(length=180), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "scope_type IN ('shared_core','industry','regional','organization') AND ((scope_type = 'organization' AND owner_organization_id IS NOT NULL) OR (scope_type <> 'organization'))",
            name="ck_canonical_event_type_scope",
        ),
        sa.ForeignKeyConstraint(
            ["applicable_entity_type_id"], ["canonical_entity_types.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type_code", "scope_key", name="uq_canonical_event_type_scope"),
    )
    op.create_index(
        "ix_canonical_event_type_code", "canonical_event_types", ["type_code"], unique=False
    )
    op.create_index(
        "ix_canonical_event_type_owner",
        "canonical_event_types",
        ["owner_organization_id"],
        unique=False,
    )
    op.create_table(
        "entity_match_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type_id", sa.Uuid(), nullable=False),
        sa.Column("rule_code", sa.String(length=150), nullable=False),
        sa.Column("match_method", sa.String(length=40), nullable=False),
        sa.Column(
            "match_fields",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("confidence_weight", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "normalization_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "match_method IN ('exact_identifier', 'normalized_identifier', 'deterministic_composite', 'fuzzy_candidate')",
            name="ck_entity_match_rule_method",
        ),
        sa.CheckConstraint(
            "confidence_weight >= 0 AND confidence_weight <= 1", name="ck_entity_match_rule_weight"
        ),
        sa.ForeignKeyConstraint(
            ["entity_type_id"], ["canonical_entity_types.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_type_id", "rule_code", name="uq_entity_match_rule_code"),
    )
    op.create_index(
        "ix_entity_match_rule_entity_type", "entity_match_rules", ["entity_type_id"], unique=False
    )
    op.create_table(
        "mapping_template_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("semantic_version", sa.String(length=30), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "definition_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "lifecycle_status IN ('draft', 'candidate', 'validated', 'approved', 'published', 'deprecated', 'retired')",
            name="ck_mapping_template_version_lifecycle",
        ),
        sa.ForeignKeyConstraint(["template_id"], ["mapping_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("template_id", "content_hash", name="uq_mapping_template_content_hash"),
        sa.UniqueConstraint(
            "template_id", "semantic_version", name="uq_mapping_template_semantic_version"
        ),
    )
    op.create_index(
        "ix_mapping_template_version_template",
        "mapping_template_versions",
        ["template_id"],
        unique=False,
    )
    op.create_index(
        "uq_mapping_template_one_published_version",
        "mapping_template_versions",
        ["template_id"],
        unique=True,
        postgresql_where=sa.text("lifecycle_status = 'published'"),
        sqlite_where=sa.text("lifecycle_status = 'published'"),
    )
    op.create_table(
        "value_crosswalk_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_organization_id", sa.Uuid(), nullable=True),
        sa.Column("crosswalk_id", sa.Uuid(), nullable=False),
        sa.Column("source_value", sa.String(length=500), nullable=False),
        sa.Column("normalized_source_value", sa.String(length=500), nullable=False),
        sa.Column("canonical_target_value", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_entry_id", sa.Uuid(), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mapping_confidence_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("confidence_method_code", sa.String(length=100), nullable=True),
        sa.Column("confidence_method_version", sa.String(length=30), nullable=True),
        sa.Column(
            "confidence_components",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("confidence_interpretation", sa.Text(), nullable=True),
        sa.Column("confidence_limitations", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'deprecated', 'retired')",
            name="ck_value_crosswalk_entry_status",
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from",
            name="ck_value_crosswalk_entry_effective_dates",
        ),
        sa.CheckConstraint(
            "mapping_confidence_score IS NULL OR (mapping_confidence_score >= 0 AND mapping_confidence_score <= 1)",
            name="ck_value_crosswalk_entry_confidence",
        ),
        sa.ForeignKeyConstraint(["crosswalk_id"], ["value_crosswalks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["owner_organization_id", "crosswalk_id"],
            ["value_crosswalks.owner_organization_id", "value_crosswalks.id"],
            name="fk_value_crosswalk_entry_owner_crosswalk",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id", "supersedes_entry_id"],
            [
                "value_crosswalk_entries.owner_organization_id",
                "value_crosswalk_entries.id",
            ],
            name="fk_value_crosswalk_entry_owner_supersedes",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_entry_id"], ["value_crosswalk_entries.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_organization_id",
            "id",
            name="uq_value_crosswalk_entries_owner_id",
        ),
        sa.UniqueConstraint(
            "crosswalk_id",
            "normalized_source_value",
            "effective_from",
            name="uq_value_crosswalk_entry_effective_source",
        ),
    )
    op.create_index(
        "ix_value_crosswalk_entry_lookup",
        "value_crosswalk_entries",
        ["crosswalk_id", "normalized_source_value", "status"],
        unique=False,
    )
    op.create_index(
        "ix_value_crosswalk_entry_owner_crosswalk",
        "value_crosswalk_entries",
        ["owner_organization_id", "crosswalk_id"],
        unique=False,
    )
    op.create_index(
        "ix_value_crosswalk_entry_owner_supersedes",
        "value_crosswalk_entries",
        ["owner_organization_id", "supersedes_entry_id"],
        unique=False,
    )
    op.create_table(
        "field_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_field_path", sa.String(length=500), nullable=False),
        sa.Column("canonical_field_definition_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("is_required_for_publication", sa.Boolean(), nullable=False),
        sa.Column(
            "default_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("sequence >= 0", name="ck_field_mapping_sequence"),
        sa.ForeignKeyConstraint(
            ["canonical_field_definition_id"],
            ["canonical_field_definitions.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_version_id"], ["mapping_template_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "template_version_id", "sequence", name="uq_field_mapping_version_sequence"
        ),
        sa.UniqueConstraint(
            "template_version_id",
            "source_field_path",
            "canonical_field_definition_id",
            name="uq_field_mapping_source_target",
        ),
    )
    op.create_index(
        "ix_field_mapping_canonical_field",
        "field_mappings",
        ["canonical_field_definition_id"],
        unique=False,
    )
    op.create_index(
        "ix_field_mapping_version", "field_mappings", ["template_version_id"], unique=False
    )
    op.create_table(
        "mapping_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("template_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_count", sa.Integer(), nullable=False),
        sa.Column("mapped_count", sa.Integer(), nullable=False),
        sa.Column("exception_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('created', 'queued', 'running', 'completed', 'partially_completed', 'failed', 'cancelled')",
            name="ck_mapping_run_status",
        ),
        sa.CheckConstraint(
            "input_count >= 0 AND mapped_count >= 0 AND exception_count >= 0 AND rejected_count >= 0",
            name="ck_mapping_run_counts",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "dataset_version_id"],
            ["dataset_versions.organization_id", "dataset_versions.id"],
            name="fk_mapping_runs_org_dataset_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["template_version_id"], ["mapping_template_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_mapping_runs_org_id"),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_mapping_run_idempotency_key"
        ),
    )
    op.create_index(
        "ix_mapping_run_org_created",
        "mapping_runs",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_mapping_run_org_dataset_version",
        "mapping_runs",
        ["organization_id", "dataset_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_mapping_run_template_version", "mapping_runs", ["template_version_id"], unique=False
    )
    op.create_table(
        "mapping_transformations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("field_mapping_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("transformation_type", sa.String(length=40), nullable=False),
        sa.Column(
            "parameters_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "transformation_type IN ('type_cast', 'date_parse', 'timezone_normalize', 'unit_convert', 'currency_normalize', 'crosswalk_lookup', 'derive', 'constant', 'trim_normalize', 'custom_function')",
            name="ck_mapping_transformation_type",
        ),
        sa.CheckConstraint("sequence >= 0", name="ck_mapping_transformation_sequence"),
        sa.ForeignKeyConstraint(["field_mapping_id"], ["field_mappings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "field_mapping_id", "sequence", name="uq_mapping_transformation_sequence"
        ),
    )
    op.create_index(
        "ix_mapping_transformation_field",
        "mapping_transformations",
        ["field_mapping_id"],
        unique=False,
    )
    op.create_table(
        "source_schemas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("schema_fingerprint", sa.String(length=255), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("discovery_method", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('unknown', 'discovered', 'stable', 'changed', 'incompatible', 'approved')",
            name="ck_source_schema_status",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "dataset_id"],
            ["datasets.organization_id", "datasets.id"],
            name="fk_source_schemas_org_dataset",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "dataset_version_id"],
            ["dataset_versions.organization_id", "dataset_versions.id"],
            name="fk_source_schemas_org_dataset_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "dataset_id",
            "schema_fingerprint",
            name="uq_source_schema_fingerprint",
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_source_schemas_org_id"),
    )
    op.create_index(
        "ix_source_schema_org_dataset",
        "source_schemas",
        ["organization_id", "dataset_id"],
        unique=False,
    )
    op.create_index(
        "ix_source_schema_org_dataset_version",
        "source_schemas",
        ["organization_id", "dataset_version_id"],
        unique=False,
    )
    op.create_table(
        "source_fields",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("source_schema_id", sa.Uuid(), nullable=False),
        sa.Column("field_path", sa.String(length=500), nullable=False),
        sa.Column("inferred_data_type", sa.String(length=50), nullable=False),
        sa.Column(
            "sample_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("null_ratio", sa.Numeric(precision=7, scale=6), nullable=True),
        sa.Column("distinct_ratio", sa.Numeric(precision=7, scale=6), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "distinct_ratio IS NULL OR (distinct_ratio >= 0 AND distinct_ratio <= 1)",
            name="ck_source_field_distinct_ratio",
        ),
        sa.CheckConstraint(
            "null_ratio IS NULL OR (null_ratio >= 0 AND null_ratio <= 1)",
            name="ck_source_field_null_ratio",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "source_schema_id"],
            ["source_schemas.organization_id", "source_schemas.id"],
            name="fk_source_fields_org_source_schema",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_schema_id", "field_path", name="uq_source_field_path"),
    )
    op.create_index(
        "ix_source_field_org_schema",
        "source_fields",
        ["organization_id", "source_schema_id"],
        unique=False,
    )
    op.create_table(
        "mapping_record_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("mapping_run_id", sa.Uuid(), nullable=False),
        sa.Column("raw_record_reference_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("canonical_target_kind", sa.String(length=20), nullable=False),
        sa.Column("canonical_target_id", sa.Uuid(), nullable=True),
        sa.Column("source_reported_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mapped_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "result_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("mapping_confidence_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("confidence_method_code", sa.String(length=100), nullable=True),
        sa.Column("confidence_method_version", sa.String(length=30), nullable=True),
        sa.Column(
            "confidence_components",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("confidence_interpretation", sa.Text(), nullable=True),
        sa.Column("confidence_limitations", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "canonical_target_kind IN ('entity', 'event', 'metric')",
            name="ck_mapping_record_result_target_kind",
        ),
        sa.CheckConstraint(
            "status IN ('mapped', 'human_confirmed', 'unresolved', 'ambiguous', 'conflicting', 'missing_required_field', 'rejected', 'superseded')",
            name="ck_mapping_record_result_status",
        ),
        sa.CheckConstraint(
            "mapping_confidence_score IS NULL OR (mapping_confidence_score >= 0 AND mapping_confidence_score <= 1)",
            name="ck_mapping_record_result_confidence",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "mapping_run_id"],
            ["mapping_runs.organization_id", "mapping_runs.id"],
            name="fk_mapping_record_results_org_mapping_run",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "raw_record_reference_id"],
            ["raw_record_references.organization_id", "raw_record_references.id"],
            name="fk_mapping_record_results_org_raw_record",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "mapping_run_id",
            "raw_record_reference_id",
            "canonical_target_kind",
            name="uq_mapping_record_result_target",
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_mapping_record_results_org_id"),
    )
    op.create_index(
        "ix_mapping_record_result_org_raw",
        "mapping_record_results",
        ["organization_id", "raw_record_reference_id"],
        unique=False,
    )
    op.create_index(
        "ix_mapping_record_result_org_run",
        "mapping_record_results",
        ["organization_id", "mapping_run_id"],
        unique=False,
    )
    op.create_table(
        "source_canonical_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("raw_record_reference_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_target_kind", sa.String(length=20), nullable=False),
        sa.Column("canonical_target_id", sa.Uuid(), nullable=False),
        sa.Column("mapping_run_id", sa.Uuid(), nullable=False),
        sa.Column("template_version_id", sa.Uuid(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("mapping_confidence_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("confidence_method_code", sa.String(length=100), nullable=True),
        sa.Column("confidence_method_version", sa.String(length=30), nullable=True),
        sa.Column(
            "confidence_components",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("confidence_interpretation", sa.Text(), nullable=True),
        sa.Column("confidence_limitations", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "canonical_target_kind IN ('entity', 'event', 'metric')",
            name="ck_source_canonical_link_target_kind",
        ),
        sa.CheckConstraint(
            "mapping_confidence_score IS NULL OR (mapping_confidence_score >= 0 AND mapping_confidence_score <= 1)",
            name="ck_source_canonical_link_confidence",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "mapping_run_id"],
            ["mapping_runs.organization_id", "mapping_runs.id"],
            name="fk_source_canonical_links_org_mapping_run",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "raw_record_reference_id"],
            ["raw_record_references.organization_id", "raw_record_references.id"],
            name="fk_source_canonical_links_org_raw_record",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["template_version_id"], ["mapping_template_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_source_canonical_links_org_id"),
        sa.UniqueConstraint(
            "organization_id",
            "raw_record_reference_id",
            "canonical_target_kind",
            "canonical_target_id",
            "mapping_run_id",
            name="uq_source_canonical_link_target",
        ),
    )
    op.create_index(
        "ix_source_canonical_link_org_raw",
        "source_canonical_links",
        ["organization_id", "raw_record_reference_id"],
        unique=False,
    )
    op.create_index(
        "ix_source_canonical_link_org_run",
        "source_canonical_links",
        ["organization_id", "mapping_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_source_canonical_link_target",
        "source_canonical_links",
        ["organization_id", "canonical_target_kind", "canonical_target_id"],
        unique=False,
    )
    op.create_table(
        "canonical_entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_entity_key", sa.String(length=500), nullable=True),
        sa.Column(
            "attributes_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("survivorship_source_link_id", sa.Uuid(), nullable=True),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("mapping_confidence_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("confidence_method_code", sa.String(length=100), nullable=True),
        sa.Column("confidence_method_version", sa.String(length=30), nullable=True),
        sa.Column(
            "confidence_components",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("confidence_interpretation", sa.Text(), nullable=True),
        sa.Column("confidence_limitations", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "mapping_confidence_score IS NULL OR (mapping_confidence_score >= 0 AND mapping_confidence_score <= 1)",
            name="ck_canonical_entity_confidence",
        ),
        sa.ForeignKeyConstraint(
            ["entity_type_id"], ["canonical_entity_types.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "survivorship_source_link_id"],
            ["source_canonical_links.organization_id", "source_canonical_links.id"],
            name="fk_canonical_entities_org_survivorship_link",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "entity_type_id",
            "canonical_entity_key",
            name="uq_canonical_entity_business_key",
        ),
        sa.UniqueConstraint(
            "organization_id",
            "content_fingerprint",
            name="uq_canonical_entity_fingerprint",
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_canonical_entities_org_id"),
    )
    op.create_index(
        "ix_canonical_entity_org_survivorship",
        "canonical_entities",
        ["organization_id", "survivorship_source_link_id"],
        unique=False,
    )
    op.create_index(
        "ix_canonical_entity_org_type",
        "canonical_entities",
        ["organization_id", "entity_type_id"],
        unique=False,
    )
    op.create_table(
        "mapping_exceptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("mapping_record_result_id", sa.Uuid(), nullable=False),
        sa.Column("exception_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "detail_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("resolution_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "exception_type IN ('unresolved_field', 'ambiguous_entity', 'conflicting_mapping', 'missing_required_field', 'transformation_failure', 'crosswalk_miss', 'validation_failure')",
            name="ck_mapping_exception_type",
        ),
        sa.CheckConstraint(
            "status IN ('open', 'under_review', 'resolved', 'wont_fix')",
            name="ck_mapping_exception_status",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "mapping_record_result_id"],
            ["mapping_record_results.organization_id", "mapping_record_results.id"],
            name="fk_mapping_exceptions_org_record_result",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_mapping_exceptions_org_id"),
    )
    op.create_index(
        "ix_mapping_exception_org_result",
        "mapping_exceptions",
        ["organization_id", "mapping_record_result_id"],
        unique=False,
    )
    op.create_index(
        "ix_mapping_exception_org_status",
        "mapping_exceptions",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_table(
        "canonical_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_entity_id", sa.Uuid(), nullable=False),
        sa.Column("event_type_id", sa.Uuid(), nullable=False),
        sa.Column("occurrence_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurrence_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurrence_precision", sa.String(length=20), nullable=False),
        sa.Column("source_reported_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_reference", sa.String(length=255), nullable=True),
        sa.Column("mapping_status", sa.String(length=40), nullable=False),
        sa.Column(
            "attributes_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("mapping_confidence_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("confidence_method_code", sa.String(length=100), nullable=True),
        sa.Column("confidence_method_version", sa.String(length=30), nullable=True),
        sa.Column(
            "confidence_components",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("confidence_interpretation", sa.Text(), nullable=True),
        sa.Column("confidence_limitations", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "mapping_status IN ('mapped', 'human_confirmed', 'unresolved', 'ambiguous', 'conflicting', 'missing_required_field', 'rejected', 'superseded')",
            name="ck_canonical_event_mapping_status",
        ),
        sa.CheckConstraint(
            "occurrence_precision IN ('instant', 'second', 'minute', 'hour', 'day', 'period')",
            name="ck_canonical_event_occurrence_precision",
        ),
        sa.CheckConstraint(
            "mapping_confidence_score IS NULL OR (mapping_confidence_score >= 0 AND mapping_confidence_score <= 1)",
            name="ck_canonical_event_confidence",
        ),
        sa.CheckConstraint(
            "occurrence_end IS NULL OR occurrence_end >= occurrence_start",
            name="ck_canonical_event_occurrence_range",
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"], ["canonical_event_types.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "canonical_entity_id"],
            ["canonical_entities.organization_id", "canonical_entities.id"],
            name="fk_canonical_events_org_entity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "content_fingerprint", name="uq_canonical_event_fingerprint"
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_canonical_events_org_id"),
    )
    op.create_index("ix_canonical_event_type", "canonical_events", ["event_type_id"], unique=False)
    op.create_index(
        "ix_canonical_events_occurrence",
        "canonical_events",
        ["organization_id", "canonical_entity_id", "occurrence_start"],
        unique=False,
    )
    op.create_table(
        "canonical_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_entity_id", sa.Uuid(), nullable=False),
        sa.Column("metric_type_id", sa.Uuid(), nullable=False),
        sa.Column("measured_value", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("occurrence_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurrence_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurrence_precision", sa.String(length=20), nullable=False),
        sa.Column("source_reported_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mapping_status", sa.String(length=40), nullable=False),
        sa.Column(
            "attributes_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("mapping_confidence_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("confidence_method_code", sa.String(length=100), nullable=True),
        sa.Column("confidence_method_version", sa.String(length=30), nullable=True),
        sa.Column(
            "confidence_components",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("confidence_interpretation", sa.Text(), nullable=True),
        sa.Column("confidence_limitations", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "mapping_status IN ('mapped', 'human_confirmed', 'unresolved', 'ambiguous', 'conflicting', 'missing_required_field', 'rejected', 'superseded')",
            name="ck_canonical_metric_mapping_status",
        ),
        sa.CheckConstraint(
            "occurrence_precision IN ('instant', 'second', 'minute', 'hour', 'day', 'period')",
            name="ck_canonical_metric_occurrence_precision",
        ),
        sa.CheckConstraint(
            "currency IS NULL OR length(currency) = 3", name="ck_canonical_metric_currency"
        ),
        sa.CheckConstraint(
            "mapping_confidence_score IS NULL OR (mapping_confidence_score >= 0 AND mapping_confidence_score <= 1)",
            name="ck_canonical_metric_confidence",
        ),
        sa.CheckConstraint(
            "occurrence_end IS NULL OR occurrence_end >= occurrence_start",
            name="ck_canonical_metric_occurrence_range",
        ),
        sa.ForeignKeyConstraint(
            ["metric_type_id"], ["canonical_metric_types.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "canonical_entity_id"],
            ["canonical_entities.organization_id", "canonical_entities.id"],
            name="fk_canonical_metrics_org_entity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "content_fingerprint", name="uq_canonical_metric_fingerprint"
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_canonical_metrics_org_id"),
    )
    op.create_index(
        "ix_canonical_metric_type", "canonical_metrics", ["metric_type_id"], unique=False
    )
    op.create_index(
        "ix_canonical_metrics_occurrence",
        "canonical_metrics",
        ["organization_id", "canonical_entity_id", "occurrence_start"],
        unique=False,
    )
    op.create_table(
        "entity_match_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("source_canonical_link_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_entity_id", sa.Uuid(), nullable=False),
        sa.Column("match_rule_id", sa.Uuid(), nullable=False),
        sa.Column("match_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('candidate', 'accepted', 'rejected', 'superseded')",
            name="ck_entity_match_candidate_status",
        ),
        sa.CheckConstraint(
            "match_score >= 0 AND match_score <= 1", name="ck_entity_match_candidate_score"
        ),
        sa.ForeignKeyConstraint(["match_rule_id"], ["entity_match_rules.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["organization_id", "candidate_entity_id"],
            ["canonical_entities.organization_id", "canonical_entities.id"],
            name="fk_entity_match_candidates_org_entity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "source_canonical_link_id"],
            ["source_canonical_links.organization_id", "source_canonical_links.id"],
            name="fk_entity_match_candidates_org_source_link",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_canonical_link_id",
            "candidate_entity_id",
            "match_rule_id",
            name="uq_entity_match_candidate",
        ),
    )
    op.create_index(
        "ix_entity_match_candidate_org_entity",
        "entity_match_candidates",
        ["organization_id", "candidate_entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_entity_match_candidate_org_link",
        "entity_match_candidates",
        ["organization_id", "source_canonical_link_id"],
        unique=False,
    )
    op.create_table(
        "mapping_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("mapping_exception_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("reviewer_user_id", sa.Uuid(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "override_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('confirm', 'override', 'reject', 'defer')",
            name="ck_mapping_review_decision",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "mapping_exception_id"],
            ["mapping_exceptions.organization_id", "mapping_exceptions.id"],
            name="fk_mapping_reviews_org_exception",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_mapping_review_org_exception",
        "mapping_reviews",
        ["organization_id", "mapping_exception_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mapping_review_org_exception", table_name="mapping_reviews")
    op.drop_table("mapping_reviews")
    op.drop_index("ix_entity_match_candidate_org_link", table_name="entity_match_candidates")
    op.drop_index("ix_entity_match_candidate_org_entity", table_name="entity_match_candidates")
    op.drop_table("entity_match_candidates")
    op.drop_index("ix_canonical_metrics_occurrence", table_name="canonical_metrics")
    op.drop_index("ix_canonical_metric_type", table_name="canonical_metrics")
    op.drop_table("canonical_metrics")
    op.drop_index("ix_canonical_events_occurrence", table_name="canonical_events")
    op.drop_index("ix_canonical_event_type", table_name="canonical_events")
    op.drop_table("canonical_events")
    op.drop_index("ix_mapping_exception_org_status", table_name="mapping_exceptions")
    op.drop_index("ix_mapping_exception_org_result", table_name="mapping_exceptions")
    op.drop_table("mapping_exceptions")
    op.drop_index("ix_canonical_entity_org_type", table_name="canonical_entities")
    op.drop_index("ix_canonical_entity_org_survivorship", table_name="canonical_entities")
    op.drop_table("canonical_entities")
    op.drop_index("ix_source_canonical_link_target", table_name="source_canonical_links")
    op.drop_index("ix_source_canonical_link_org_run", table_name="source_canonical_links")
    op.drop_index("ix_source_canonical_link_org_raw", table_name="source_canonical_links")
    op.drop_table("source_canonical_links")
    op.drop_index("ix_mapping_record_result_org_run", table_name="mapping_record_results")
    op.drop_index("ix_mapping_record_result_org_raw", table_name="mapping_record_results")
    op.drop_table("mapping_record_results")
    op.drop_index("ix_source_field_org_schema", table_name="source_fields")
    op.drop_table("source_fields")
    op.drop_index("ix_source_schema_org_dataset_version", table_name="source_schemas")
    op.drop_index("ix_source_schema_org_dataset", table_name="source_schemas")
    op.drop_table("source_schemas")
    op.drop_index("ix_mapping_transformation_field", table_name="mapping_transformations")
    op.drop_table("mapping_transformations")
    op.drop_index("ix_mapping_run_template_version", table_name="mapping_runs")
    op.drop_index("ix_mapping_run_org_dataset_version", table_name="mapping_runs")
    op.drop_index("ix_mapping_run_org_created", table_name="mapping_runs")
    op.drop_table("mapping_runs")
    op.drop_index("ix_field_mapping_version", table_name="field_mappings")
    op.drop_index("ix_field_mapping_canonical_field", table_name="field_mappings")
    op.drop_table("field_mappings")
    op.drop_index("ix_value_crosswalk_entry_owner_crosswalk", table_name="value_crosswalk_entries")
    op.drop_index("ix_value_crosswalk_entry_lookup", table_name="value_crosswalk_entries")
    op.drop_table("value_crosswalk_entries")
    op.drop_index(
        "uq_mapping_template_one_published_version",
        table_name="mapping_template_versions",
        postgresql_where=sa.text("lifecycle_status = 'published'"),
        sqlite_where=sa.text("lifecycle_status = 'published'"),
    )
    op.drop_index("ix_mapping_template_version_template", table_name="mapping_template_versions")
    op.drop_table("mapping_template_versions")
    op.drop_index("ix_entity_match_rule_entity_type", table_name="entity_match_rules")
    op.drop_table("entity_match_rules")
    op.drop_index("ix_canonical_event_type_owner", table_name="canonical_event_types")
    op.drop_index("ix_canonical_event_type_code", table_name="canonical_event_types")
    op.drop_table("canonical_event_types")
    op.drop_index("ix_value_crosswalk_owner", table_name="value_crosswalks")
    op.drop_index("ix_value_crosswalk_code", table_name="value_crosswalks")
    op.drop_table("value_crosswalks")
    op.drop_index("ix_mapping_template_owner", table_name="mapping_templates")
    op.drop_index("ix_mapping_template_industry", table_name="mapping_templates")
    op.drop_index("ix_mapping_template_code", table_name="mapping_templates")
    op.drop_table("mapping_templates")
    op.drop_index("ix_mapping_audit_org_time", table_name="mapping_audit_events")
    op.drop_index("ix_mapping_audit_entity", table_name="mapping_audit_events")
    op.drop_table("mapping_audit_events")
    op.drop_index("ix_canonical_metric_type_owner", table_name="canonical_metric_types")
    op.drop_index("ix_canonical_metric_type_code", table_name="canonical_metric_types")
    op.drop_table("canonical_metric_types")
    op.drop_index("ix_canonical_entity_type_owner", table_name="canonical_entity_types")
    op.drop_index("ix_canonical_entity_type_code", table_name="canonical_entity_types")
    op.drop_table("canonical_entity_types")
    op.drop_index("ix_canonical_field_type", table_name="canonical_field_definitions")
    op.drop_table("canonical_field_definitions")
    with op.batch_alter_table("lineage_edges") as batch_op:
        batch_op.drop_constraint("ck_lineage_edge_relationship", type_="check")
        batch_op.create_check_constraint(
            "ck_lineage_edge_relationship",
            f"relationship_type IN ({LEGACY_LINEAGE_RELATIONSHIP_VALUES})",
        )

    with op.batch_alter_table("lineage_nodes") as batch_op:
        batch_op.drop_constraint("ck_lineage_node_type", type_="check")
        batch_op.create_check_constraint(
            "ck_lineage_node_type",
            f"node_type IN ({LEGACY_LINEAGE_NODE_VALUES})",
        )

    with op.batch_alter_table("raw_record_references") as batch_op:
        batch_op.drop_constraint("uq_raw_record_references_org_id", type_="unique")
    # ### end Alembic commands ###
