"""decision intelligence optimization

Revision ID: 20260807_0033
Revises: 20260806_0032
Create Date: 2026-08-05 16:53:25.968044
"""

import json
from collections.abc import Sequence
from datetime import UTC, datetime
from hashlib import sha256
from uuid import UUID, uuid5

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "20260807_0033"
down_revision: str | None = "20260806_0032"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sa.String(length=50), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "event_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_decision_audit_idempotency"
        ),
    )
    op.create_index(
        "ix_decision_audit_org_entity",
        "decision_audit_events",
        ["organization_id", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_audit_org_time",
        "decision_audit_events",
        ["organization_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "decision_method_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("method_code", sa.String(length=150), nullable=False),
        sa.Column("method_name", sa.String(length=250), nullable=False),
        sa.Column("method_class", sa.String(length=80), nullable=False),
        sa.Column("method_version", sa.String(length=30), nullable=False),
        sa.Column("solver_adapter", sa.String(length=100), nullable=False),
        sa.Column("solver_adapter_version", sa.String(length=30), nullable=False),
        sa.Column(
            "supported_variable_types",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "supported_constraint_types",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "supported_objective_types",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "parameter_schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("deterministic", sa.Boolean(), nullable=False),
        sa.Column("exact_or_heuristic", sa.String(length=30), nullable=False),
        sa.Column("optimality_guarantee", sa.String(length=120), nullable=False),
        sa.Column("default_time_limit_seconds", sa.Integer(), nullable=False),
        sa.Column("max_supported_problem_size", sa.Integer(), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_key", sa.String(length=180), nullable=False),
        sa.Column("owner_organization_id", sa.Uuid(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "lifecycle_status IN ('draft', 'active', 'deprecated', 'retired')",
            name="ck_decision_method_status",
        ),
        sa.CheckConstraint(
            "scope_type IN ('shared_core', 'industry', 'regional', 'organization')",
            name="ck_decision_method_scope_type",
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "method_code",
            "method_version",
            "scope_key",
            name="uq_decision_method_code_version_scope",
        ),
    )
    op.create_index(
        "ix_decision_method_class", "decision_method_definitions", ["method_class"], unique=False
    )
    op.create_index(
        "ix_decision_method_code", "decision_method_definitions", ["method_code"], unique=False
    )
    op.create_index(
        "ix_decision_method_owner",
        "decision_method_definitions",
        ["owner_organization_id"],
        unique=False,
    )
    method_table = sa.table(
        "decision_method_definitions",
        sa.column("id", sa.Uuid()),
        sa.column("method_code", sa.String()),
        sa.column("method_name", sa.String()),
        sa.column("method_class", sa.String()),
        sa.column("method_version", sa.String()),
        sa.column("solver_adapter", sa.String()),
        sa.column("solver_adapter_version", sa.String()),
        sa.column("supported_variable_types", sa.JSON()),
        sa.column("supported_constraint_types", sa.JSON()),
        sa.column("supported_objective_types", sa.JSON()),
        sa.column("parameter_schema", sa.JSON()),
        sa.column("deterministic", sa.Boolean()),
        sa.column("exact_or_heuristic", sa.String()),
        sa.column("optimality_guarantee", sa.String()),
        sa.column("default_time_limit_seconds", sa.Integer()),
        sa.column("max_supported_problem_size", sa.Integer()),
        sa.column("lifecycle_status", sa.String()),
        sa.column("scope_type", sa.String()),
        sa.column("scope_key", sa.String()),
        sa.column("owner_organization_id", sa.Uuid()),
        sa.column("content_hash", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    method_specs = (
        (
            "scipy_milp_portfolio",
            "SciPy MILP Portfolio Selection",
            "mixed_integer_linear_programming",
            "scipy.optimize.milp",
            "exact",
        ),
        (
            "scipy_linear_program",
            "SciPy Linear Programming",
            "linear_programming",
            "scipy.optimize.linprog",
            "exact",
        ),
        (
            "scipy_hungarian_assignment",
            "SciPy Hungarian Assignment",
            "assignment",
            "scipy.optimize.linear_sum_assignment",
            "exact",
        ),
        (
            "python_critical_path",
            "Deterministic Critical Path",
            "critical_path",
            "pure_python",
            "exact",
        ),
        (
            "deterministic_greedy",
            "Deterministic Governed Greedy",
            "deterministic_greedy",
            "pure_python",
            "heuristic",
        ),
        (
            "weighted_scoring",
            "Governed Weighted Scoring",
            "weighted_scoring",
            "pure_python",
            "heuristic",
        ),
        (
            "lexicographic_optimization",
            "Lexicographic Optimization",
            "lexicographic_optimization",
            "scipy.optimize.milp",
            "exact",
        ),
        ("bounded_scheduling", "Bounded Scheduling", "scheduling", "pure_python", "exact"),
        ("bounded_sequencing", "Bounded Sequencing", "sequencing", "pure_python", "exact"),
        (
            "bounded_resource_allocation",
            "Bounded Resource Allocation",
            "resource_allocation",
            "scipy.optimize.linear_sum_assignment",
            "exact",
        ),
        (
            "bounded_portfolio_selection",
            "Bounded Portfolio Selection",
            "portfolio_selection",
            "scipy.optimize.milp",
            "exact",
        ),
        (
            "bounded_constraint_satisfaction",
            "Bounded Constraint Satisfaction",
            "constraint_satisfaction",
            "pure_python",
            "heuristic",
        ),
    )
    namespace = UUID("d15c1510-2b14-4b00-a000-000000000001")
    seeded_at = datetime(2026, 8, 7, tzinfo=UTC)
    op.bulk_insert(
        method_table,
        [
            {
                "id": uuid5(namespace, code),
                "method_code": code,
                "method_name": name,
                "method_class": method_class,
                "method_version": "1.0.0",
                "solver_adapter": adapter,
                "solver_adapter_version": "bounded-v1",
                "supported_variable_types": op.inline_literal(
                    json.dumps(["binary", "integer", "continuous", "assignment", "sequence"]),
                    type_=sa.Text(),
                ),
                "supported_constraint_types": op.inline_literal(
                    json.dumps(
                        ["resource", "capacity", "budget", "workforce", "time", "dependency"]
                    ),
                    type_=sa.Text(),
                ),
                "supported_objective_types": op.inline_literal(
                    json.dumps(["maximize", "minimize", "lexicographic"]),
                    type_=sa.Text(),
                ),
                "parameter_schema": op.inline_literal("{}", type_=sa.Text()),
                "deterministic": True,
                "exact_or_heuristic": exactness,
                "optimality_guarantee": (
                    "optimal when solved" if exactness == "exact" else "no optimality guarantee"
                ),
                "default_time_limit_seconds": 30,
                "max_supported_problem_size": 500,
                "lifecycle_status": "active",
                "scope_type": "shared_core",
                "scope_key": "shared_core",
                "owner_organization_id": None,
                "content_hash": sha256(f"{code}:1.0.0:{adapter}:{exactness}".encode()).hexdigest(),
                "created_at": seeded_at,
                "updated_at": seeded_at,
            }
            for code, name, method_class, adapter, exactness in method_specs
        ],
        multiinsert=False,
    )
    op.create_table(
        "decision_problems",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("problem_code", sa.String(length=150), nullable=False),
        sa.Column("problem_name", sa.String(length=250), nullable=False),
        sa.Column("use_case_code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_key", sa.String(length=180), nullable=False),
        sa.Column("owner_organization_id", sa.Uuid(), nullable=True),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "lifecycle_status IN ('draft', 'active', 'deprecated', 'retired')",
            name="ck_decision_problem_status",
        ),
        sa.CheckConstraint(
            "scope_type IN ('shared_core', 'industry', 'regional', 'organization')",
            name="ck_decision_problem_scope_type",
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("problem_code", "scope_key", name="uq_decision_problem_code_scope"),
    )
    op.create_index("ix_decision_problem_code", "decision_problems", ["problem_code"], unique=False)
    op.create_index(
        "ix_decision_problem_owner", "decision_problems", ["owner_organization_id"], unique=False
    )
    op.create_index(
        "ix_decision_problem_status", "decision_problems", ["lifecycle_status"], unique=False
    )
    op.create_table(
        "decision_problem_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("objective_strategy", sa.String(length=50), nullable=False),
        sa.Column(
            "input_contract",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "output_contract",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "assumptions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "limitations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("supersedes_version_id", sa.Uuid(), nullable=True),
        sa.Column("published_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "lifecycle_status IN ('draft', 'published', 'superseded', 'retired')",
            name="ck_decision_problem_version_status",
        ),
        sa.ForeignKeyConstraint(["problem_id"], ["decision_problems.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["supersedes_version_id"], ["decision_problem_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("problem_id", "version", name="uq_decision_problem_version"),
    )
    op.create_index(
        "ix_decision_problem_version_problem",
        "decision_problem_versions",
        ["problem_id", "lifecycle_status"],
        unique=False,
    )
    op.create_table(
        "decision_constraints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("problem_version_id", sa.Uuid(), nullable=False),
        sa.Column("constraint_code", sa.String(length=120), nullable=False),
        sa.Column("constraint_type", sa.String(length=80), nullable=False),
        sa.Column("operator", sa.String(length=10), nullable=False),
        sa.Column("right_hand_value", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("hard_constraint", sa.Boolean(), nullable=False),
        sa.Column("unit_code", sa.String(length=50), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column(
            "expression",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_version_id"], ["decision_problem_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "problem_version_id", "constraint_code", name="uq_decision_constraint_code"
        ),
    )
    op.create_index(
        "ix_decision_constraint_problem_version",
        "decision_constraints",
        ["problem_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_constraint_type", "decision_constraints", ["constraint_type"], unique=False
    )
    op.create_table(
        "decision_objectives",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("problem_version_id", sa.Uuid(), nullable=False),
        sa.Column("objective_code", sa.String(length=120), nullable=False),
        sa.Column("objective_type", sa.String(length=50), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("source_metric", sa.String(length=150), nullable=False),
        sa.Column("weight", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("priority_order", sa.Integer(), nullable=False),
        sa.Column("unit_code", sa.String(length=50), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column(
            "parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("weight >= 0", name="ck_decision_objective_weight"),
        sa.ForeignKeyConstraint(
            ["problem_version_id"], ["decision_problem_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "problem_version_id", "objective_code", name="uq_decision_objective_code"
        ),
    )
    op.create_index(
        "ix_decision_objective_problem_version",
        "decision_objectives",
        ["problem_version_id"],
        unique=False,
    )
    op.create_table(
        "decision_scenarios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("problem_version_id", sa.Uuid(), nullable=False),
        sa.Column("method_definition_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_name", sa.String(length=250), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("scenario_horizon_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scenario_horizon_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column("scenario_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("validation_status", sa.String(length=30), nullable=False),
        sa.Column(
            "gate_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("superseded_by_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "lifecycle_status IN ('draft', 'validating', 'ready', 'blocked', "
            "'executing', 'completed', 'superseded', 'cancelled')",
            name="ck_decision_scenario_status",
        ),
        sa.ForeignKeyConstraint(
            ["method_definition_id"], ["decision_method_definitions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["problem_version_id"], ["decision_problem_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_decision_scenarios_org_id"),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_decision_scenario_idempotency"
        ),
    )
    op.create_index(
        "ix_decision_scenario_fingerprint",
        "decision_scenarios",
        ["organization_id", "scenario_fingerprint"],
        unique=False,
    )
    op.create_index(
        "ix_decision_scenario_org_problem",
        "decision_scenarios",
        ["organization_id", "problem_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_scenario_org_status",
        "decision_scenarios",
        ["organization_id", "lifecycle_status"],
        unique=False,
    )
    op.create_table(
        "decision_variable_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("problem_version_id", sa.Uuid(), nullable=False),
        sa.Column("variable_code", sa.String(length=120), nullable=False),
        sa.Column("variable_type", sa.String(length=40), nullable=False),
        sa.Column("lower_bound", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("upper_bound", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("unit_code", sa.String(length=50), nullable=True),
        sa.Column(
            "domain_contract",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_version_id"], ["decision_problem_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "problem_version_id", "variable_code", name="uq_decision_variable_code"
        ),
    )
    op.create_index(
        "ix_decision_variable_problem_version",
        "decision_variable_definitions",
        ["problem_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_variable_type",
        "decision_variable_definitions",
        ["variable_type"],
        unique=False,
    )
    op.create_table(
        "decision_executions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.Uuid(), nullable=False),
        sa.Column("method_code", sa.String(length=150), nullable=False),
        sa.Column("method_version", sa.String(length=30), nullable=False),
        sa.Column("solver_adapter", sa.String(length=100), nullable=False),
        sa.Column("solver_adapter_version", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("scenario_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=True),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=False),
        sa.Column("optimality_gap", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "objective_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "violations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "warnings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "assumptions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "reproducibility_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "gate_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'validating', 'blocked', 'running', "
            "'solved_optimal', 'solved_feasible', 'infeasible', 'unbounded', "
            "'timed_out', 'failed', 'cancelled')",
            name="ck_decision_execution_status",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "scenario_id"],
            ["decision_scenarios.organization_id", "decision_scenarios.id"],
            name="fk_decision_executions_org_scenario",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_decision_executions_org_id"),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_decision_execution_idempotency"
        ),
    )
    op.create_index(
        "ix_decision_execution_input_fingerprint",
        "decision_executions",
        ["organization_id", "input_fingerprint"],
        unique=False,
    )
    op.create_index(
        "ix_decision_execution_org_scenario",
        "decision_executions",
        ["organization_id", "scenario_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_execution_org_status",
        "decision_executions",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_table(
        "decision_scenario_inputs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.Uuid(), nullable=False),
        sa.Column("input_kind", sa.String(length=80), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_version", sa.String(length=64), nullable=True),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("mapping_confidence", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("trust_readiness_status", sa.String(length=40), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "input_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "validation_flags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "scenario_id"],
            ["decision_scenarios.organization_id", "decision_scenarios.id"],
            name="fk_decision_scenario_inputs_org_scenario",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scenario_id", "input_kind", "source_id", name="uq_decision_scenario_input_source"
        ),
    )
    op.create_index(
        "ix_decision_scenario_input_kind",
        "decision_scenario_inputs",
        ["organization_id", "scenario_id", "input_kind"],
        unique=False,
    )
    op.create_index(
        "ix_decision_scenario_input_org_scenario",
        "decision_scenario_inputs",
        ["organization_id", "scenario_id"],
        unique=False,
    )
    op.create_table(
        "decision_solutions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("solution_number", sa.Integer(), nullable=False),
        sa.Column("feasibility_status", sa.String(length=30), nullable=False),
        sa.Column("solver_status", sa.String(length=50), nullable=False),
        sa.Column(
            "objective_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "variable_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "binding_constraints",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "violations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "solver_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "execution_id"],
            ["decision_executions.organization_id", "decision_executions.id"],
            name="fk_decision_solutions_org_execution",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("execution_id", "solution_number", name="uq_decision_solution_number"),
        sa.UniqueConstraint("organization_id", "id", name="uq_decision_solutions_org_id"),
    )
    op.create_index(
        "ix_decision_solution_org_execution",
        "decision_solutions",
        ["organization_id", "execution_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_solution_org_feasibility",
        "decision_solutions",
        ["organization_id", "feasibility_status"],
        unique=False,
    )
    op.create_table(
        "decision_alternatives",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("solution_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("feasible", sa.Boolean(), nullable=False),
        sa.Column(
            "objective_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expected_value", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("expected_recovery", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("expected_cost", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("expected_risk", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("expected_duration_hours", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column(
            "binding_constraints",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "soft_constraint_violations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("tradeoff_narrative", sa.Text(), nullable=False),
        sa.Column(
            "assumptions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "supporting_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "solution_id"],
            ["decision_solutions.organization_id", "decision_solutions.id"],
            name="fk_decision_alternatives_org_solution",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_decision_alternatives_org_id"),
        sa.UniqueConstraint("solution_id", "rank", name="uq_decision_alternative_rank"),
    )
    op.create_index(
        "ix_decision_alternative_org_rank",
        "decision_alternatives",
        ["organization_id", "solution_id", "rank"],
        unique=False,
    )
    op.create_index(
        "ix_decision_alternative_org_solution",
        "decision_alternatives",
        ["organization_id", "solution_id"],
        unique=False,
    )
    op.create_table(
        "decision_sensitivity_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("solution_id", sa.Uuid(), nullable=False),
        sa.Column("parameter_code", sa.String(length=120), nullable=False),
        sa.Column("perturbation_type", sa.String(length=50), nullable=False),
        sa.Column("original_value", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("perturbed_value", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("objective_change", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("recommendation_stable", sa.Boolean(), nullable=False),
        sa.Column("break_even_value", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("shadow_price", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column(
            "result_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "solution_id"],
            ["decision_solutions.organization_id", "decision_solutions.id"],
            name="fk_decision_sensitivity_results_org_solution",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_decision_sensitivity_factor",
        "decision_sensitivity_results",
        ["organization_id", "solution_id", "parameter_code"],
        unique=False,
    )
    op.create_index(
        "ix_decision_sensitivity_org_solution",
        "decision_sensitivity_results",
        ["organization_id", "solution_id"],
        unique=False,
    )
    op.create_table(
        "decision_recommendations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("solution_id", sa.Uuid(), nullable=False),
        sa.Column("selected_alternative_id", sa.Uuid(), nullable=False),
        sa.Column("approved_by_approval_id", sa.Uuid(), nullable=True),
        sa.Column("converted_action_id", sa.Uuid(), nullable=True),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "objective_explanation",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "constraint_explanation",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "evidence_summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "lifecycle_status <> 'converted_to_action' OR "
            "(approved_by_approval_id IS NOT NULL AND converted_action_id IS NOT NULL)",
            name="ck_decision_recommendation_conversion",
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('proposed', 'reviewed', 'approved', 'rejected', "
            "'converted_to_action', 'superseded', 'expired')",
            name="ck_decision_recommendation_status",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "converted_action_id"],
            ["operational_actions.organization_id", "operational_actions.id"],
            name="fk_decision_recommendations_org_action",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "selected_alternative_id"],
            ["decision_alternatives.organization_id", "decision_alternatives.id"],
            name="fk_decision_recommendations_org_alternative",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "solution_id"],
            ["decision_solutions.organization_id", "decision_solutions.id"],
            name="fk_decision_recommendations_org_solution",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_decision_recommendations_org_id"),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_decision_recommendation_idempotency"
        ),
    )
    op.create_index(
        "ix_decision_recommendation_org_action",
        "decision_recommendations",
        ["organization_id", "converted_action_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_recommendation_org_alternative",
        "decision_recommendations",
        ["organization_id", "selected_alternative_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_recommendation_org_approval",
        "decision_recommendations",
        ["organization_id", "approved_by_approval_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_recommendation_org_solution",
        "decision_recommendations",
        ["organization_id", "solution_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_recommendation_org_status",
        "decision_recommendations",
        ["organization_id", "lifecycle_status"],
        unique=False,
    )
    op.create_table(
        "decision_approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("reviewer_user_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_role", sa.String(length=50), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('approve', 'reject', 'defer', 'request_changes')",
            name="ck_decision_approval_decision",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "recommendation_id"],
            ["decision_recommendations.organization_id", "decision_recommendations.id"],
            name="fk_decision_approvals_org_recommendation",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_decision_approvals_org_id"),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_decision_approval_idempotency"
        ),
    )
    op.create_index(
        "ix_decision_approval_org_decision",
        "decision_approvals",
        ["organization_id", "decision"],
        unique=False,
    )
    op.create_index(
        "ix_decision_approval_org_recommendation",
        "decision_approvals",
        ["organization_id", "recommendation_id", "created_at"],
        unique=False,
    )
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table("decision_recommendations", recreate="always") as batch_op:
            batch_op.create_foreign_key(
                "fk_decision_recommendations_org_approval",
                "decision_approvals",
                ["organization_id", "approved_by_approval_id"],
                ["organization_id", "id"],
                ondelete="RESTRICT",
            )
    else:
        op.create_foreign_key(
            "fk_decision_recommendations_org_approval",
            "decision_recommendations",
            "decision_approvals",
            ["organization_id", "approved_by_approval_id"],
            ["organization_id", "id"],
            ondelete="RESTRICT",
        )
    op.create_table(
        "decision_outcome_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("operational_action_id", sa.Uuid(), nullable=False),
        sa.Column("action_outcome_id", sa.Uuid(), nullable=True),
        sa.Column("outcome_evidence_kind", sa.String(length=80), nullable=True),
        sa.Column("outcome_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("verification_status", sa.String(length=40), nullable=False),
        sa.Column("reconciliation_status", sa.String(length=40), nullable=False),
        sa.Column("expected_value_reference", sa.String(length=255), nullable=True),
        sa.Column("actual_value_reference", sa.String(length=255), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "action_outcome_id"],
            ["action_outcomes.organization_id", "action_outcomes.id"],
            name="fk_decision_outcome_links_org_action_outcome",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "operational_action_id"],
            ["operational_actions.organization_id", "operational_actions.id"],
            name="fk_decision_outcome_links_org_action",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "recommendation_id"],
            ["decision_recommendations.organization_id", "decision_recommendations.id"],
            name="fk_decision_outcome_links_org_recommendation",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "recommendation_id",
            "outcome_evidence_kind",
            "outcome_evidence_id",
            name="uq_decision_outcome_evidence",
        ),
    )
    op.create_index(
        "ix_decision_outcome_evidence",
        "decision_outcome_links",
        ["organization_id", "outcome_evidence_kind", "outcome_evidence_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_outcome_org_action",
        "decision_outcome_links",
        ["organization_id", "operational_action_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_outcome_org_action_outcome",
        "decision_outcome_links",
        ["organization_id", "action_outcome_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_outcome_org_recommendation",
        "decision_outcome_links",
        ["organization_id", "recommendation_id"],
        unique=False,
    )
    op.create_table(
        "decision_recommendation_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_kind", sa.String(length=80), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("relevance", sa.String(length=30), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "recommendation_id"],
            ["decision_recommendations.organization_id", "decision_recommendations.id"],
            name="fk_decision_recommendation_evidence_org_recommendation",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "recommendation_id",
            "evidence_kind",
            "evidence_id",
            name="uq_decision_recommendation_evidence_reference",
        ),
    )
    op.create_index(
        "ix_decision_rec_evidence_org_recommendation",
        "decision_recommendation_evidence",
        ["organization_id", "recommendation_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_rec_evidence_reference",
        "decision_recommendation_evidence",
        ["organization_id", "evidence_kind", "evidence_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table("decision_recommendations", recreate="always") as batch_op:
            batch_op.drop_constraint(
                "fk_decision_recommendations_org_approval",
                type_="foreignkey",
            )
    else:
        op.drop_constraint(
            "fk_decision_recommendations_org_approval",
            "decision_recommendations",
            type_="foreignkey",
        )
    op.drop_index(
        "ix_decision_rec_evidence_reference", table_name="decision_recommendation_evidence"
    )
    op.drop_index(
        "ix_decision_rec_evidence_org_recommendation", table_name="decision_recommendation_evidence"
    )
    op.drop_table("decision_recommendation_evidence")
    op.drop_index("ix_decision_outcome_org_recommendation", table_name="decision_outcome_links")
    op.drop_index("ix_decision_outcome_org_action_outcome", table_name="decision_outcome_links")
    op.drop_index("ix_decision_outcome_org_action", table_name="decision_outcome_links")
    op.drop_index("ix_decision_outcome_evidence", table_name="decision_outcome_links")
    op.drop_table("decision_outcome_links")
    op.drop_index("ix_decision_approval_org_recommendation", table_name="decision_approvals")
    op.drop_index("ix_decision_approval_org_decision", table_name="decision_approvals")
    op.drop_table("decision_approvals")
    op.drop_index("ix_decision_recommendation_org_status", table_name="decision_recommendations")
    op.drop_index("ix_decision_recommendation_org_solution", table_name="decision_recommendations")
    op.drop_index("ix_decision_recommendation_org_approval", table_name="decision_recommendations")
    op.drop_index(
        "ix_decision_recommendation_org_alternative", table_name="decision_recommendations"
    )
    op.drop_index("ix_decision_recommendation_org_action", table_name="decision_recommendations")
    op.drop_table("decision_recommendations")
    op.drop_index("ix_decision_sensitivity_org_solution", table_name="decision_sensitivity_results")
    op.drop_index("ix_decision_sensitivity_factor", table_name="decision_sensitivity_results")
    op.drop_table("decision_sensitivity_results")
    op.drop_index("ix_decision_alternative_org_solution", table_name="decision_alternatives")
    op.drop_index("ix_decision_alternative_org_rank", table_name="decision_alternatives")
    op.drop_table("decision_alternatives")
    op.drop_index("ix_decision_solution_org_feasibility", table_name="decision_solutions")
    op.drop_index("ix_decision_solution_org_execution", table_name="decision_solutions")
    op.drop_table("decision_solutions")
    op.drop_index("ix_decision_scenario_input_org_scenario", table_name="decision_scenario_inputs")
    op.drop_index("ix_decision_scenario_input_kind", table_name="decision_scenario_inputs")
    op.drop_table("decision_scenario_inputs")
    op.drop_index("ix_decision_execution_org_status", table_name="decision_executions")
    op.drop_index("ix_decision_execution_org_scenario", table_name="decision_executions")
    op.drop_index("ix_decision_execution_input_fingerprint", table_name="decision_executions")
    op.drop_table("decision_executions")
    op.drop_index("ix_decision_variable_type", table_name="decision_variable_definitions")
    op.drop_index(
        "ix_decision_variable_problem_version", table_name="decision_variable_definitions"
    )
    op.drop_table("decision_variable_definitions")
    op.drop_index("ix_decision_scenario_org_status", table_name="decision_scenarios")
    op.drop_index("ix_decision_scenario_org_problem", table_name="decision_scenarios")
    op.drop_index("ix_decision_scenario_fingerprint", table_name="decision_scenarios")
    op.drop_table("decision_scenarios")
    op.drop_index("ix_decision_objective_problem_version", table_name="decision_objectives")
    op.drop_table("decision_objectives")
    op.drop_index("ix_decision_constraint_type", table_name="decision_constraints")
    op.drop_index("ix_decision_constraint_problem_version", table_name="decision_constraints")
    op.drop_table("decision_constraints")
    op.drop_index("ix_decision_problem_version_problem", table_name="decision_problem_versions")
    op.drop_table("decision_problem_versions")
    op.drop_index("ix_decision_problem_status", table_name="decision_problems")
    op.drop_index("ix_decision_problem_owner", table_name="decision_problems")
    op.drop_index("ix_decision_problem_code", table_name="decision_problems")
    op.drop_table("decision_problems")
    op.drop_index("ix_decision_method_owner", table_name="decision_method_definitions")
    op.drop_index("ix_decision_method_code", table_name="decision_method_definitions")
    op.drop_index("ix_decision_method_class", table_name="decision_method_definitions")
    op.drop_table("decision_method_definitions")
    op.drop_index("ix_decision_audit_org_time", table_name="decision_audit_events")
    op.drop_index("ix_decision_audit_org_entity", table_name="decision_audit_events")
    op.drop_table("decision_audit_events")
    # ### end Alembic commands ###
